Repository marc2332/freya, pull requests merged in 2023-12, with the labels that each got.

#410 Fix window icons which don't have a 32 bit depth
  .gitignore
  crates/renderer/src/config.rs
Labels: fix 🩹

#413 book: Add always up-to-date component reference
  book/src/guides/components.md
Labels: documentation

#415 book: Add imports to hot reload chapter
  book/src/guides/hot_reload.md
Labels: documentation

#397 feat: Opacity attribute
  book/src/guides/style.md
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window.rs
  crates/state/src/style.rs
  examples/opacity.rs
Labels: enhancement 🔥

#408 Mention the fact that the book uses some APIs from the git version
  book/src/index.md
Labels: documentation, enhancement 🔥

#394 feat: Performance Overlay Plugin
  crates/core/src/plugins.rs
  crates/engine/src/mocked.rs
  crates/freya/src/lib.rs
  crates/freya/src/plugins/mod.rs
  crates/freya/src/plugins/performance_overlay.rs
  crates/renderer/src/app.rs
  crates/torin/src/torin.rs
  examples/performance_overlay_plugin.rs
  examples/plugin.rs
Labels: enhancement 🔥, devtools

#425 feat: Per-component themes
  book/src/guides/theming.md
  crates/components/src/accordion.rs
  crates/components/src/body.rs
  crates/components/src/button.rs
  crates/components/src/canvas.rs
  crates/components/src/dropdown.rs
  crates/components/src/external_link.rs
  crates/components/src/graph.rs
  crates/components/src/icons/arrow.rs
  crates/components/src/input.rs
  crates/components/src/loader.rs
  crates/components/src/network_image.rs
  crates/components/src/progress_bar.rs
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_thumb.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/components/src/table.rs
  crates/components/src/tooltip.rs
  crates/devtools/src/lib.rs
  crates/devtools/src/tab.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
  crates/freya/src/_docs/theming.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/lib.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/use_theme.rs
  examples/accessibility.rs
  examples/accordion.rs
  examples/canvas.rs
  examples/cloned_editor.rs
  examples/custom_theme.rs
  examples/dynamic_theme.rs
  examples/editor.rs
  examples/material_design_app.rs
  examples/paragraph.rs
  examples/render_canvas.rs
  examples/shader.rs
  examples/sidebar.rs
  examples/simple_editor.rs
  examples/switch_theme.rs
  examples/text.rs
  examples/ui.rs
  examples/virtual_scroll_view.rs
Labels: enhancement 🔥, breaking

#431 Versioned docs: better warnings + fix some typos
  crates/freya/src/_docs/animating.rs
  crates/freya/src/_docs/theming.rs
Labels: documentation

#390 feat: Installer example with cargo-packager
  Cargo.toml
  examples/installer/Cargo.toml
  examples/installer/assets/icon.ico
  examples/installer/assets/icon.png
  examples/installer/build.rs
  examples/installer/src/main.rs
Labels: documentation, enhancement 🔥

#430 fix: Touch start and end events were not triggering pointer events
  crates/core/src/events/events_measurer.rs
  crates/core/tests/pointer_events.rs
Labels: fix 🩹

#421 feat: New viewport size unit
  crates/components/src/external_link.rs
  crates/elements/src/_docs/size_unit.rs
  crates/state/src/values/size.rs
  crates/torin/src/measure.rs
  crates/torin/src/torin.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
  examples/viewport.rs
Labels: enhancement 🔥, fix 🩹

#407 Create publishing chapter
  book/src/SUMMARY.md
  book/src/guides/publishing.md
Labels: documentation, enhancement 🔥

#435 Fix English in the main crate docs
  crates/freya/src/_docs/animating.rs
  crates/freya/src/_docs/devtools.rs
  crates/freya/src/_docs/hot_reload.rs
  crates/freya/src/_docs/testing.rs
  crates/freya/src/_docs/theming.rs
  crates/freya/src/lib.rs
Labels: documentation

#441 bench: Update torin benchmarks
  crates/torin/benches/bench.rs
Labels: tests/benchs📦

#444 Improve `OrderDirection` docs
  crates/components/src/table.rs
Labels: documentation

#445 chore: Clean up `freya-testing`
  crates/components/src/drag_drop.rs
  crates/core/tests/pointer_events.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/tests/use_editable.rs
  crates/testing/src/launch.rs
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
  crates/testing/src/test_node.rs
  crates/testing/src/test_utils.rs
Labels: chore

#442 chore: `ScrollBar` offset props must be component props not part of a theme
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
Labels: enhancement 🔥

#443 feat: Turn `TextEvent` from an enum into flags
  crates/hooks/Cargo.toml
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
Labels: enhancement 🔥

#439 perf: Slightly faster layout measurement in torin
  .github/workflows/benchmarks.yml
  crates/dom/src/dom_adapter.rs
  crates/torin/src/measure.rs
  crates/torin/src/torin.rs
  crates/torin/tests/other.rs
Labels: enhancement 🔥, performance ⚡️

#355 fix: Abandon context if not current when closing the app
  crates/engine/src/mocked.rs
  crates/renderer/src/window.rs
Labels: fix 🩹, skia 🖌️
