Repository marc2332/freya, pull requests merged in 2023-03, with the labels that each got.

#82 feat: Hot reload
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  components/Cargo.toml
  core/Cargo.toml
  docs/src/SUMMARY.md
  docs/src/basic_app.md
  docs/src/hotreload.md
  elements/Cargo.toml
  elements/src/lib.rs
  examples/hotreload.rs
  freya/Cargo.toml
  freya/src/lib.rs
  hooks/Cargo.toml
  layout/Cargo.toml
  readme.md
  renderer/Cargo.toml
  renderer/src/lib.rs
  renderer/src/window.rs
  state/Cargo.toml
  testing/Cargo.toml
Labels: enhancement

#96 feat: Multiple font families support
  Cargo.lock
  layout/src/lib.rs
  renderer/src/elements/label.rs
  renderer/src/elements/paragraph.rs
  state/Cargo.toml
  state/src/font_style.rs
  state/src/lib.rs
Labels: enhancement

#97 feat: Clean up examples
  examples/animation.rs
  examples/app_dog.rs
  examples/center.rs
  examples/hotreload.rs
  examples/image.rs
  examples/layers.rs
  examples/mouse.rs
  examples/paddings.rs
  examples/progress_bars.rs
  examples/showcase.rs
  examples/test.rs
  renderer/src/lib.rs
Labels: enhancement

#102 feat: Reduce CPU usage
  Cargo.lock
  common/src/event_messages.rs
  common/src/lib.rs
  hooks/Cargo.toml
  hooks/src/use_editable.rs
  renderer/src/lib.rs
  renderer/src/window.rs
Labels: enhancement

#103 Update macOS setup description
  docs/src/setup.md
Labels: documentation

#104 feat: Simplified code + performance boost
  core/Cargo.toml
  core/src/dom.rs
  core/src/lib.rs
  devtools/Cargo.toml
  devtools/src/lib.rs
  freya/Cargo.toml
  freya/src/launch.rs
  hooks/src/use_camera.rs
  layout/src/area_calc.rs
  layout/src/layers.rs
  layout/src/lib.rs
  layout/tests/layouts.rs
  renderer/src/elements/image.rs
  renderer/src/elements/label.rs
  renderer/src/elements/paragraph.rs
  renderer/src/elements/rect_container.rs
  renderer/src/elements/svg.rs
  renderer/src/lib.rs
  renderer/src/renderer.rs
  renderer/src/window.rs
  testing/src/lib.rs
Labels: enhancement

#106 refactor: Refactor freya-renderer code
  core/src/events.rs
  core/src/lib.rs
  examples/animation.rs
  examples/app_dog.rs
  examples/canvas.rs
  examples/drag.rs
  examples/editor.rs
  examples/mouse.rs
  examples/progress_bars.rs
  examples/showcase.rs
  examples/switch.rs
  examples/ui.rs
  examples/virtual_scroll_view.rs
  hooks/tests/use_editable.rs
  renderer/src/app.rs
  renderer/src/lib.rs
  renderer/src/window.rs
  testing/src/lib.rs
Labels: enhancement

#116 feat: Virtualizing docs
  components/src/scroll_views/virtual_scroll_view.rs
  devtools/src/tabs/tree.rs
  docs/src/SUMMARY.md
  docs/src/guides/hello_world.md
  docs/src/guides/hot_reload.md
  docs/src/guides/virtual_scroll_view.png
  docs/src/guides/virtualizing.md
  examples/virtual_scroll_view.rs
Labels: documentation, enhancement

#113 feat: Rotate effect
  elements/src/lib.rs
  examples/mouse_trace.rs
  examples/rotate.rs
  renderer/src/renderer.rs
  renderer/src/window.rs
  state/src/lib.rs
  state/src/transform.rs
Labels: enhancement

#108 feat: Skia-safe v0.60
  Cargo.lock
  core/Cargo.toml
  core/src/events.rs
  devtools/Cargo.toml
  devtools/src/tabs/tree.rs
  elements/Cargo.toml
  elements/src/events_data/keyboard.rs
  elements/src/events_data/mouse.rs
  freya/Cargo.toml
  hooks/Cargo.toml
  hooks/src/use_camera.rs
  hooks/src/use_editable.rs
  layout/Cargo.toml
  renderer/Cargo.toml
  renderer/src/app.rs
  renderer/src/lib.rs
  renderer/src/window.rs
  state/Cargo.toml
  testing/Cargo.toml
  testing/tests/test.rs
Labels: enhancement, skia

#115 feat: Loader component
  Cargo.lock
  components/Cargo.toml
  components/src/lib.rs
  components/src/loader.rs
  examples/app_dog.rs
  hooks/src/use_theme.rs
Labels: enhancement

#129 feat: Use use_ref instead of use_state for ScrollViews
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
Labels: enhancement

#126 feat: Improved horizontal scrolling
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
  elements/src/events_data/wheel.rs
Labels: enhancement

#123 feat: Theming guide
  docs/src/SUMMARY.md
  docs/src/guides/theming.md
  examples/custom_theme.rs
Labels: documentation, enhancement

#124 feat: Touch events
  core/src/events.rs
  core/src/lib.rs
  elements/src/events_data.rs
  elements/src/events_data/touch.rs
  elements/src/lib.rs
  examples/touch.rs
  renderer/src/lib.rs
Labels: enhancement

#137 feat: Clean up imports
  Cargo.lock
  components/Cargo.toml
  components/src/accordion.rs
  components/src/button.rs
  components/src/dropdown.rs
  components/src/external_link.rs
  components/src/input.rs
  components/src/loader.rs
  components/src/network_image.rs
  components/src/router_link.rs
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
  components/src/slider.rs
  components/src/switch.rs
  components/src/tooltip.rs
  core/src/events.rs
  devtools/src/lib.rs
  devtools/src/node.rs
  devtools/src/property.rs
  devtools/src/tab.rs
  devtools/src/tabs/style.rs
  elements/src/elements.rs
  elements/src/events.rs
  elements/src/events/keyboard.rs
  elements/src/events/mouse.rs
  elements/src/events/touch.rs
  elements/src/events/wheel.rs
  elements/src/lib.rs
  examples/animation.rs
  examples/canvas.rs
  examples/editor.rs
  examples/hotreload.rs
  freya/src/lib.rs
  hooks/src/text_editor.rs
  hooks/src/use_editable.rs
  hooks/tests/use_editable.rs
  renderer/src/lib.rs
  testing/src/lib.rs
  testing/tests/test.rs
Labels: enhancement

#138 feat: Refactor freya-testing
  devtools/src/lib.rs
  hooks/src/use_animation.rs
  hooks/src/use_focus.rs
  hooks/tests/use_editable.rs
  testing/Cargo.toml
  testing/src/lib.rs
  testing/tests/test.rs
Labels: enhancement

#139 fix: Fixed freya-dom & freya-layout small bugs
  core/src/lib.rs
  layout/src/layers.rs
  layout/src/lib.rs
  renderer/src/elements/image.rs
  renderer/src/elements/label.rs
  renderer/src/elements/paragraph.rs
  renderer/src/elements/rect_container.rs
  renderer/src/elements/svg.rs
  renderer/src/renderer.rs
  renderer/src/window.rs
  renderer/src/wireframe.rs
Labels: bug

#133 feat: Layout docs
  docs/src/SUMMARY.md
  docs/src/guides/layout.md
Labels: enhancement

#132 feat: New use_animation
  components/src/accordion.rs
  components/src/switch.rs
  examples/animation.rs
  examples/drawer.rs
  hooks/src/use_animation.rs
Labels: enhancement
