Repository marc2332/freya, pull requests merged in 2023-06, with the labels that each got.

#209 feat: Maintain order of Nodes in layers
  core/src/lib.rs
  layout/src/layers.rs
Labels: enhancement

#188 feat: use_animation_transition
  examples/transition.rs
  hooks/src/animation.rs
  hooks/src/lib.rs
  hooks/src/use_animation.rs
  hooks/src/use_animation_transition.rs
Labels: enhancement, experiment 🧪

#191 feat: Animation docs
  book/src/SUMMARY.md
  book/src/guides/animating.md
Labels: documentation

#187 feat: Testing docs
  book/src/SUMMARY.md
  book/src/guides/testing.md
Labels: documentation

#203 feat: Pointer events
  .github/workflows/rust.yml
  Cargo.lock
  components/src/drag_drop.rs
  components/src/gesture_area.rs
  core/Cargo.toml
  core/src/events.rs
  core/src/lib.rs
  core/tests/events.rs
  elements/src/elements.rs
  elements/src/events.rs
  elements/src/events/pointer.rs
  examples/pointer.rs
  hooks/src/use_animation.rs
  hooks/src/use_focus.rs
  hooks/tests/use_editable.rs
  renderer/src/lib.rs
  testing/tests/test.rs
Labels: enhancement

#215 feat: `use_platform`
  components/src/cursor_area.rs
  components/src/graph.rs
  examples/render_canvas.rs
  examples/shader.rs
  hooks/src/lib.rs
  hooks/src/use_camera.rs
  hooks/src/use_editable.rs
  hooks/src/use_platform.rs
  testing/src/lib.rs
Labels: enhancement

#219 feat: Refactor big modules
  core/src/dom_events.rs
  core/src/events.rs
  core/src/events_processor.rs
  core/src/freya_events.rs
  core/src/layers.rs
  core/src/layout.rs
  core/src/lib.rs
  core/src/render.rs
  core/src/viewports.rs
  core/tests/events.rs
  devtools/src/tabs/style.rs
  freya/src/launch.rs
  renderer/src/app.rs
  renderer/src/event_loop.rs
  renderer/src/lib.rs
  renderer/src/renderer.rs
  renderer/src/window.rs
  testing/src/launch.rs
  testing/src/lib.rs
  testing/src/test_handler.rs
  testing/src/test_node.rs
  testing/src/test_utils.rs
Labels: enhancement

#212 feat: Layout tab in Devtools
  Cargo.toml
  README.md
  book/src/guides/hello_world.md
  devtools/Cargo.toml
  devtools/src/lib.rs
  devtools/src/tab.rs
  devtools/src/tabs/layout.rs
  devtools/src/tabs/mod.rs
  renderer/src/app.rs
Labels: enhancement, devtools

#221 feat: Refactor devtools mutations notification
  devtools/src/lib.rs
  freya/src/launch.rs
  renderer/src/app.rs
  renderer/src/lib.rs
Labels: enhancement, devtools

#226 docs: misc introduction fixes
  book/src/index.md
Labels: documentation

#222 feat(breaking): Extended font styling
  elements/src/elements.rs
  examples/canvas.rs
  examples/editor.rs
  examples/font_style.rs
  layout/src/lib.rs
  renderer/src/elements/label.rs
  state/src/font_style.rs
Labels: enhancement

#218 feat: Skia-safe v0.63
  Cargo.toml
Labels: skia

#229 feat: Remove redundant state from Graph
  components/src/graph.rs
Labels: enhancement

#228 feat: Only cache hovered elements
  core/src/events_processor.rs
Labels: enhancement

#230 feat: Initial implementation of borders
  elements/src/elements.rs
  examples/border.rs
  renderer/src/elements/rect_container.rs
  state/src/style.rs
  state/tests/parse_border.rs
Labels: enhancement

#235 feat: Added border to devtools
  core/src/node.rs
  devtools/src/property.rs
  devtools/src/tabs/style.rs
Labels: enhancement, devtools

#234 feat: Per-corner rounded corners
  core/src/node.rs
  devtools/src/tabs/style.rs
  examples/radius.rs
  renderer/src/elements/rect_container.rs
  state/src/style.rs
  torin/src/lib.rs
  torin/src/radius.rs
Labels: enhancement

#236 feat: CSS-like shadows
  components/src/button.rs
  components/src/dropdown.rs
  components/src/input.rs
  core/src/node.rs
  devtools/src/property.rs
  examples/camera.rs
  examples/canvas.rs
  examples/drag.rs
  examples/editor.rs
  examples/radius.rs
  examples/shadow.rs
  renderer/src/elements/rect_container.rs
  state/src/style.rs
  state/tests/parse_shadows.rs
Labels: enhancement

#232 feat: Rename scroll_x to offset_x and scroll_y to offset_y
  book/src/guides/animating.md
  components/src/drag_drop.rs
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
  components/src/slider.rs
  components/src/switch.rs
  core/src/node.rs
  devtools/src/node.rs
  dom/src/dom_adapter.rs
  elements/src/elements.rs
  examples/animation.rs
  examples/canvas.rs
  examples/drag.rs
  examples/mouse_trace.rs
  examples/transition.rs
  state/src/size.rs
  torin/src/node.rs
  torin/src/torin.rs
Labels: enhancement, breaking

#238 feat: text decorations, word/letter spacing, font styling refactors
  elements/src/elements.rs
  examples/font_style.rs
  layout/src/lib.rs
  renderer/src/elements/label.rs
  state/src/font_style.rs
Labels: enhancement

#240 fix: Stack ontouchmove
  core/src/events.rs
Labels: enhancement

#227 feat: More documentation
  book/book.toml
  book/src/SUMMARY.md
  book/src/guides/components.md
  book/src/guides/effects.md
  book/src/guides/elements.md
  book/src/guides/font_style.md
  book/src/guides/layout.md
  book/src/guides/style.md
  book/src/guides/theming.md
  elements/src/elements.rs
Labels: documentation

#242 feat: Better logging
  Cargo.toml
  dom/Cargo.toml
  dom/src/dom.rs
  freya/Cargo.toml
  freya/src/launch.rs
  freya/src/lib.rs
  layout/src/layers.rs
  renderer/Cargo.toml
  renderer/src/app.rs
  state/src/layout.rs
  state/src/references.rs
  state/src/style.rs
  state/src/transform.rs
  torin/src/torin.rs
Labels: enhancement

#244 feat: Input customization
  components/src/input.rs
  examples/input.rs
Labels: enhancement

#243 docs: Improved docs
  README.md
  book/src/SUMMARY.md
  book/src/demo.png
  book/src/differences_with_dioxus.md
  book/src/guides/animating.md
  book/src/guides/effects.md
  book/src/guides/elements.md
  book/src/guides/font_style.md
  book/src/guides/getting_started.md
  book/src/guides/hot_reload.md
  book/src/guides/layout.md
  book/src/guides/style.md
  book/src/guides/testing.md
  book/src/guides/theming.md
  book/src/guides/virtualizing.md
  book/src/index.md
  book/src/what_is_freya.md
Labels: documentation

#250 fix: Use inner area as root's cached parent area, in torin
  torin/src/torin.rs
Labels: enhancement

#249 feat: `overflow` attribute
  README.md
  book/src/guides/animating.md
  book/src/guides/elements.md
  book/src/guides/getting_started.md
  book/src/guides/layout.md
  book/src/guides/style.md
  book/src/guides/testing.md
  book/src/index.md
  components/src/accordion.rs
  components/src/button.rs
  components/src/canvas.rs
  components/src/dropdown.rs
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
  components/src/slider.rs
  core/src/viewports.rs
  devtools/src/lib.rs
  devtools/src/property.rs
  devtools/src/tab.rs
  devtools/src/tabs/layout.rs
  devtools/src/tabs/style.rs
  elements/src/elements.rs
  examples/animation.rs
  examples/app_dog.rs
  examples/border.rs
  examples/canvas.rs
  examples/counter.rs
  examples/drag.rs
  examples/external_link.rs
  examples/focus.rs
  examples/font_style.rs
  examples/hotreload.rs
  examples/input.rs
  examples/massive.rs
  examples/paddings.rs
  examples/pointer.rs
  examples/radius.rs
  examples/shadow.rs
  examples/text.rs
  examples/transition.rs
  examples/ui.rs
  freya/src/lib.rs
  renderer/src/elements/mod.rs
  renderer/src/elements/rect.rs
  renderer/src/renderer.rs
  state/src/style.rs
  state/src/values/color.rs
  state/src/values/mod.rs
  state/src/values/overflow.rs
  testing/tests/test.rs
Labels: enhancement

#251 feat: Improved ScrollBar and ScrollThumb
  components/src/scroll_views/mod.rs
  components/src/scroll_views/scroll_bar.rs
  components/src/scroll_views/scroll_thumb.rs
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
Labels: enhancement

#253 feat: Improved scrollbar dragging
  components/src/scroll_views/scroll_view.rs
  components/src/scroll_views/virtual_scroll_view.rs
Labels: enhancement

#254 fix: Documentation fixes
  book/src/guides/layout.md
  book/src/guides/style.md
  book/src/guides/theming.md
Labels: documentation

#255 feat: Improved slider dragging
  components/src/slider.rs
Labels: enhancement

#231 feat: `margin` support
  book/src/guides/layout.md
  components/src/button.rs
  components/src/switch.rs
  core/src/node.rs
  core/src/render.rs
  devtools/src/tabs/style.rs
  dom/src/dom_adapter.rs
  elements/src/elements.rs
  examples/border.rs
  examples/margin.rs
  examples/massive.rs
  examples/scroll.rs
  state/src/layout.rs
  state/src/values/gaps.rs
  state/src/values/mod.rs
  state/tests/parse_gaps.rs
  state/tests/parse_paddings.rs
  torin/readme.md
  torin/src/dom_adapter.rs
  torin/src/geometry.rs
  torin/src/lib.rs
  torin/src/node.rs
  torin/src/torin.rs
  torin/src/values/gaps.rs
  torin/src/values/mod.rs
  torin/tests/test.rs
Labels: enhancement

#100 feat: Accessibility support via AccessKit
  Cargo.toml
  common/Cargo.toml
  common/src/event_messages.rs
  components/Cargo.toml
  components/src/button.rs
  components/src/dropdown.rs
  components/src/input.rs
  components/src/network_image.rs
  core/Cargo.toml
  core/src/accessibility.rs
  core/src/accessibility_state.rs
  core/src/lib.rs
  devtools/src/lib.rs
  dom/src/dom.rs
  elements/Cargo.toml
  elements/src/elements.rs
  examples/accessibility.rs
  examples/canvas.rs
  examples/focus.rs
  examples/input.rs
  freya/src/launch.rs
  hooks/Cargo.toml
  hooks/src/lib.rs
  hooks/src/use_accessibility.rs
  hooks/src/use_focus.rs
  hooks/src/use_theme.rs
  layout/Cargo.toml
  renderer/Cargo.toml
  renderer/src/accessibility.rs
  renderer/src/app.rs
  renderer/src/event_loop.rs
  renderer/src/lib.rs
  renderer/src/window.rs
  state/Cargo.toml
  state/src/custom_attributes.rs
  state/src/values/accessibility.rs
  state/src/values/mod.rs
  testing/Cargo.toml
  testing/src/launch.rs
  testing/src/test_handler.rs
Labels: enhancement, accessibility 🦾

#260 fix(torin): Default max sizing to the minimum if not specified
  torin/src/torin.rs
Labels: enhancement

#261 fix: Prevent Switch from animating when it has just been mounted
  components/src/switch.rs
Labels: enhancement

#256 feat: Linear gradient fill
  core/src/events.rs
  core/src/node.rs
  devtools/src/property.rs
  devtools/src/tabs/style.rs
  examples/gradient.rs
  renderer/src/elements/rect.rs
  state/src/font_style.rs
  state/src/lib.rs
  state/src/parsing.rs
  state/src/style.rs
  state/src/values/border.rs
  state/src/values/color.rs
  state/src/values/fill.rs
  state/src/values/gradient.rs
  state/src/values/mod.rs
  state/src/values/shadow.rs
  state/tests/parse_border.rs
  state/tests/parse_color.rs
  state/tests/parse_gradient.rs
  state/tests/parse_shadows.rs
Labels: enhancement

#257 refactor(breaking): `corner_radius`, `corner_smoothing`
  book/src/guides/style.md
  components/src/accordion.rs
  components/src/button.rs
  components/src/dropdown.rs
  components/src/input.rs
  components/src/scroll_views/scroll_thumb.rs
  components/src/slider.rs
  components/src/switch.rs
  components/src/tooltip.rs
  core/src/node.rs
  devtools/src/node.rs
  devtools/src/property.rs
  devtools/src/tab.rs
  devtools/src/tabs/layout.rs
  devtools/src/tabs/style.rs
  elements/src/elements.rs
  examples/animation.rs
  examples/app_dog.rs
  examples/border.rs
  examples/canvas.rs
  examples/corner_radius.rs
  examples/drag.rs
  examples/editor.rs
  examples/frameless_window.rs
  examples/mouse_trace.rs
  examples/shadow.rs
  examples/stateful_window.rs
  examples/transition.rs
  examples/ui.rs
  renderer/src/elements/rect.rs
  state/src/style.rs
  state/src/values/corner_radius.rs
  state/src/values/mod.rs
  state/src/values/radius.rs
  state/tests/parse_corner_radius.rs
  torin/src/values/mod.rs
  torin/src/values/radius.rs
Labels: enhancement

#258 chore: Bump to latest dioxus
  Cargo.toml
  README.md
  book/src/guides/getting_started.md
  examples/en-US.json
  examples/es-ES.json
  examples/i18n.rs
  examples/shader.rs
Labels: enhancement, dioxus🧬

#265 refactor(breaking): Consistency for rotation units
  book/src/guides/effects.md
  book/src/guides/style.md
  components/src/loader.rs
  examples/i18n.rs
  examples/rotate.rs
  state/src/transform.rs
  state/src/values/color.rs
  state/tests/parse_color.rs
Labels: enhancement

#252 feat: Default to Light theme instead of Dark
  components/src/dropdown.rs
  components/src/input.rs
  components/src/tooltip.rs
  examples/app_dog.rs
  examples/canvas.rs
  examples/cloned_editor.rs
  examples/editor.rs
  examples/external_link.rs
  examples/mouse_trace.rs
  examples/paragraph.rs
  examples/shadow.rs
  examples/switch_theme.rs
  examples/text.rs
  hooks/src/use_theme.rs
Labels: experiment 🧪
