Repository marc2332/freya, pull requests merged in 2023-10, with the labels that each got.

#300 feat: ProgressBar component
  book/src/guides/components.md
  crates/components/src/lib.rs
  crates/components/src/progress_bar.rs
  crates/hooks/src/use_theme.rs
  examples/progress_bar.rs
Labels: enhancement 🔥

#313 feat: General cleanup of freya's components
  book/src/guides/animating.md
  crates/components/Cargo.toml
  crates/components/src/accordion.rs
  crates/components/src/dropdown.rs
  crates/components/src/external_link.rs
  crates/components/src/gesture_area.rs
  crates/components/src/graph.rs
  crates/components/src/input.rs
  crates/components/src/loader.rs
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_thumb.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/components/src/tooltip.rs
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_animation_transition.rs
  crates/testing/tests/test.rs
  examples/canvas.rs
Labels: enhancement 🔥, performance ⚡️

#317 feat: Skip measuring of cached siblings in layout
  .github/workflows/rust.yml
  crates/dom/src/dom_adapter.rs
  crates/torin/Cargo.toml
  crates/torin/benches/bench.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/torin.rs
  crates/torin/tests/test.rs
Labels: enhancement 🔥, experiment 🧪, performance ⚡️

#319 feat: Skia-safe v0.66.3
  Cargo.toml
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/renderer/src/window.rs
  crates/state/src/font_style.rs
Labels: enhancement 🔥, skia 🖌️, dependencies

#314 feat: Improved measuring of cached layout
  crates/torin/src/torin.rs
  crates/torin/tests/test.rs
Labels: enhancement 🔥, experiment 🧪, performance ⚡️

#321 feat: Avoid extra animations overhead
  crates/engine/src/skia.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_animation_transition.rs
  crates/renderer/src/window.rs
Labels: enhancement 🔥

#323 chore: Disable web dioxus features
  Cargo.toml
  README.md
  book/src/guides/getting_started.md
Labels: enhancement 🔥

#325 feat: Password mode for `Input` component
  crates/components/src/input.rs
  examples/password.rs
Labels: enhancement 🔥

#338 feat: Add support to customize text color inside progress bar component
  crates/components/src/progress_bar.rs
  crates/hooks/src/use_theme.rs
Labels: enhancement 🔥

#331 feat: min_width + min_height and max_width + max_height window modifiers
  crates/renderer/src/config.rs
  crates/renderer/src/window.rs
Labels: enhancement 🔥

#333 feat: Add hover and active effects for the scrollbar thumbs
  crates/components/src/scroll_views/scroll_thumb.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/hooks/src/use_theme.rs
Labels: enhancement 🔥

#298 feat: Table component
  Cargo.toml
  crates/components/src/lib.rs
  crates/components/src/table.rs
  crates/elements/src/elements.rs
  crates/hooks/src/use_theme.rs
  examples/table.rs
Labels: enhancement 🔥

#318 feat: New torin benchmark
  .github/workflows/benchmarks.yml
  .github/workflows/rust.yml
  Cargo.toml
  crates/freya/Cargo.toml
  crates/state/Cargo.toml
  crates/torin/Cargo.toml
  crates/torin/benches/bench.rs
  crates/torin/src/torin.rs
  crates/torin/tests/test.rs
Labels: enhancement 🔥, ci-cd 🤖

#345 feat: Event Loop ticker for components
  .vscode/settings.json
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_animation_transition.rs
  crates/hooks/src/use_camera.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_node.rs
  crates/hooks/src/use_platform.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/testing/src/config.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, experiment 🧪, performance ⚡️

#349 fix: Update cursor position after updating text
  crates/components/src/input.rs
  crates/hooks/src/rope_editor.rs
Labels: fix 🩹

#352 feat: `set_cursor` shortcut
  crates/components/src/cursor_area.rs
  crates/hooks/src/use_platform.rs
Labels: enhancement 🔥

#359 feat: `set_cursor` shortcut
  crates/components/src/cursor_area.rs
  crates/hooks/src/use_platform.rs
Labels: enhancement 🔥

#332 chore: Rename 'align' attribute to 'text_align'
  book/src/guides/font_style.md
  crates/components/src/dropdown.rs
  crates/components/src/network_image.rs
  crates/components/src/progress_bar.rs
  crates/devtools/src/tab.rs
  crates/devtools/src/tabs/layout.rs
  crates/elements/src/elements.rs
  crates/layout/src/measurer.rs
  crates/state/src/font_style.rs
  examples/animation.rs
  examples/custom_font.rs
  examples/gesture_area.rs
  examples/paragraph.rs
  examples/text.rs
  examples/tic_tac_toe.rs
  examples/transition.rs
Labels: enhancement 🔥

#360 fix: mouseenter wasn't being emitted when mouseover was emitted at the same time
  crates/core/src/events_processor.rs
Labels: fix 🩹

#353 feat: Improve and optimize elements clipping
  crates/core/src/viewports.rs
  crates/renderer/src/renderer.rs
Labels: enhancement 🔥, performance ⚡️
