Repository marc2332/freya, pull requests merged in 2023-09, with the labels that each got.

#237 feat: Sidebar example
  Cargo.toml
  examples/sidebar.rs
Labels: enhancement, experiment 🧪

#275 feat: Material Design example
  examples/material_design_app.rs
Labels: experiment 🧪

#294 feat: Set cursor to default on unmount in `CursorArea`
  crates/components/src/cursor_area.rs
Labels: enhancement

#295 feat: Tic Tac Toe example
  examples/tic_tac_toe.rs
Labels: enhancement

#277 feat: Torin benchmarks
  .github/workflows/benchmarks.yml
  crates/torin/Cargo.toml
  crates/torin/benches/bench.rs
Labels: enhancement, experiment 🧪

#296 feat: Clean and refactor some internals
  crates/devtools/src/lib.rs
  crates/dom/src/dom.rs
  crates/layout/src/layers.rs
  crates/layout/src/lib.rs
  crates/layout/src/measurer.rs
Labels: enhancement

#301 fix: Manually request redraw after resize on macOS
  crates/renderer/src/window.rs
Labels: bug-fix

#303 fix: Filter invalid children in `DioxusDOMAdapter::children_of`
  crates/dom/src/dom_adapter.rs
Labels: bug-fix

#305 feat: Cache nodes validations
  crates/core/src/layout.rs
  crates/dom/src/dom.rs
  crates/dom/src/dom_adapter.rs
  crates/torin/benches/bench.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/torin.rs
  crates/torin/tests/test.rs
Labels: enhancement

#308 docs: Arch Linux setup instructions
  book/src/setup.md
Labels: documentation

#311 fix: Use main branch as base for ci benchmarks
  .github/workflows/benchmarks.yml
Labels: fix

#310 feat: Use FxHashSet for dirty nodes in Torin
  crates/torin/src/torin.rs
  crates/torin/tests/test.rs
Labels: enhancement, performance

#315 feat: New torin benchmark for invalidations in the middle of the tree
  crates/torin/benches/bench.rs
Labels: enhancement, ci-cd

#316 fix: Properly pass children ids in torin benchmarks
  crates/torin/benches/bench.rs
Labels: fix

#309 fix(docs): Update Torin's link in differences with Dioxus
  book/src/differences_with_dioxus.md
Labels: documentation, fix

#312 feat: Pass the initial value of use_animation in a callback
  book/src/guides/animating.md
  crates/components/src/accordion.rs
  crates/components/src/switch.rs
  crates/hooks/src/use_animation.rs
  examples/animation.rs
Labels: enhancement
