Repository marc2332/freya, pull requests merged in 2024-11, with the labels that each got.

#985 feat: Consider antialising for incremental rendering
  crates/core/src/elements/utils.rs
  crates/core/src/render/compositor.rs
Labels: enhancement 🔥, fix 🩹

#920 feat: flex support
  crates/elements/src/_docs/attributes/content.md
  crates/elements/src/_docs/size_unit.rs
  crates/state/src/values/content.rs
  crates/state/src/values/size.rs
  crates/torin/src/measure.rs
  crates/torin/src/values/content.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/flex.rs
  examples/flex.rs
  examples/flex_2.rs
Labels: enhancement 🔥, layout 📐

#999 refactor: Remove `DirtyNodesResults` from `native-core`
  crates/core/src/dom/doms.rs
  crates/native-core/Cargo.toml
  crates/native-core/src/lib.rs
  crates/native-core/src/passes.rs
  crates/native-core/src/real_dom.rs
Labels: internal impovement👍

#1001 refactor: Remove `anymap`
  crates/native-core-macro/src/lib.rs
  crates/native-core/Cargo.toml
  crates/native-core/src/lib.rs
  crates/native-core/src/passes.rs
Labels: internal impovement👍

#998 fix: Use paragraph's full width if text align is non-start
  crates/core/src/elements/paragraph.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/render/utils/label.rs
  crates/core/src/render/utils/paragraph.rs
Labels: fix 🩹

#797 enhancement: add support for `fill` in `svg`
  crates/components/src/svg.rs
  crates/core/src/elements/svg.rs
  crates/core/src/node.rs
  crates/devtools/src/tabs/style.rs
  crates/elements/src/_docs/attributes/fill_stroke.md
  crates/elements/src/definitions.rs
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/native-core/src/attributes.rs
  crates/state/src/style.rs
  examples/settings.svg
  examples/svg_fill.rs
Labels: enhancement 🔥

#988 Add prefixes and parentheses to calc function
  crates/state/Cargo.toml
  crates/state/src/values/size.rs
  crates/state/tests/parse_size.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥

#1006 Fix scale factor behavior in `calc()`
  crates/torin/src/lib.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥
