Repository marc2332/freya, pull requests merged in 2024-08, with the labels that each got.

#776 feat: Add missing gradient functions
  .vscode/settings.json
  crates/core/src/elements/rect.rs
  crates/core/src/node.rs
  crates/devtools/src/property.rs
  crates/devtools/src/tabs/style.rs
  crates/engine/src/mocked.rs
  crates/state/src/values/fill.rs
  crates/state/src/values/gradient.rs
  crates/state/tests/parse_gradient.rs
  examples/gradient.rs
Labels: enhancement 🔥

#801 fix: Show missing attributes in devtools
  crates/core/src/node.rs
  crates/devtools/src/tabs/style.rs
  crates/torin/src/values/content.rs
  crates/torin/src/values/position.rs
Labels: fix 🩹

#790 feat: `import_svg` macro
  crates/components/src/lib.rs
  crates/components/src/svg.rs
  examples/import_svg.rs
Labels: enhancement 🔥

#784 feat: Support percentage of auto in layout
  crates/components/src/accordion.rs
  crates/state/src/values/size.rs
  crates/torin/src/geometry.rs
  crates/torin/src/measure.rs
  crates/torin/src/torin.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥

#808 feat: Avoid copying images when rendering
  crates/core/src/elements/image.rs
Labels: enhancement 🔥, performance ⚡️

#809 feat: Add `performance-overlay` feature to `freya` crate
  Cargo.toml
  crates/freya/Cargo.toml
  crates/freya/src/launch.rs
Labels: enhancement 🔥

#821 feat: Ignore unnecessary dioxus vdom mutations
  crates/core/src/dom/mutations_writer.rs
Labels: enhancement 🔥, performance ⚡️

#818 chore: Rust 1.80.1
  rust-toolchain.toml
Labels: ci-cd 🤖

#827 fix: Force the dropdown items vertically
  crates/components/src/dropdown.rs
Labels: fix 🩹

#813 Add opengl_rtt example.
  Cargo.toml
  crates/components/src/graph.rs
  crates/core/src/elements/rect.rs
  crates/hooks/src/use_canvas.rs
  crates/renderer/src/window_state.rs
  crates/state/src/custom_attributes.rs
  examples/opengl_rtt.rs
  examples/render_canvas.rs
  examples/shader.rs
  examples/shader_editor.rs
Labels: enhancement 🔥

#807 feat: Refactor some parts of Torin
  crates/torin/src/dom_adapter.rs
  crates/torin/src/geometry.rs
  crates/torin/src/lib.rs
  crates/torin/src/measure.rs
  crates/torin/src/measure_mode.rs
  crates/torin/src/torin.rs
Labels: internal impovement👍

#793 feat: `PluginHandle`
  .github/workflows/rust.yml
  Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/lib.rs
  crates/components/src/native_container.rs
  crates/core/Cargo.toml
  crates/core/src/dom/doms.rs
  crates/core/src/event_messages.rs
  crates/core/src/lib.rs
  crates/core/src/plugins.rs
  crates/core/src/skia/paragraph.rs
  crates/freya/src/lib.rs
  crates/freya/src/plugins/performance_overlay.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_platform.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window_state.rs
  crates/renderer/src/winit_waker.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/gamepad_focus.rs
  examples/gamepad_trace.rs
  examples/plugin.rs
  examples/render_canvas.rs
Labels: enhancement 🔥
