Repository marc2332/freya, pull requests merged in 2024-02, with the labels that each got.

#268 feat: Proper event bubbling
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/freya_events.rs
  crates/core/tests/event_bubbling.rs
  crates/renderer/src/app.rs
  crates/testing/src/test_handler.rs
  examples/floating_editors.rs
Labels: enhancement 🔥, experiment 🧪

#470 feat: Memoized Focused Node
  crates/hooks/src/use_focus.rs
Labels: enhancement 🔥

#388 feat: Clipboard integration in `use_editable`
  Cargo.toml
  crates/hooks/Cargo.toml
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
Labels: enhancement 🔥, blocked

#483 feat: Reduce deps
  Cargo.toml
  crates/components/Cargo.toml
  crates/components/src/gesture_area.rs
  crates/core/Cargo.toml
  crates/freya/Cargo.toml
  crates/renderer/Cargo.toml
  crates/renderer/src/app.rs
  crates/state/Cargo.toml
Labels: enhancement 🔥, blocked

#496 fix: Incorrect behavior of use_animation_transition
  crates/hooks/src/use_animation_transition.rs
Labels: fix 🩹

#498 feat: Prevent unrequested redraw
  crates/common/src/event_messages.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/window.rs
Labels: enhancement 🔥

#492 chore: Simplify freya-renderer crate
  crates/common/src/event_messages.rs
  crates/core/src/render.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/window.rs
  crates/renderer/src/winit_waker.rs
Labels: blocked

#495 chore: Fix link of freya_elements docs in nightly docs
  .github/workflows/deploy_docs.yml
  crates/freya/src/lib.rs
Labels: documentation, ci-cd 🤖

#500 feat: Derive Copy for freya-hooks
  Cargo.toml
  crates/components/src/accordion.rs
  crates/components/src/button.rs
  crates/components/src/cursor_area.rs
  crates/components/src/dropdown.rs
  crates/components/src/input.rs
  crates/components/src/network_image.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_animation_transition.rs
  crates/hooks/src/use_camera.rs
  crates/hooks/src/use_canvas.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_node.rs
  crates/hooks/src/use_platform.rs
  crates/hooks/tests/use_animation.rs
  crates/hooks/tests/use_editable.rs
  examples/app_dog.rs
  examples/cloned_editor.rs
  examples/floating_editors.rs
  examples/i18n.rs
  examples/progress_bar.rs
  examples/shader.rs
  examples/simple_editor.rs
Labels: enhancement 🔥

#472 feat: Undo & redo integration for `use_editable`
  .github/workflows/rust.yml
  crates/hooks/src/editor_history.rs
  crates/hooks/src/lib.rs
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_animation.rs
Labels: enhancement 🔥, blocked

#480 feat: `Input` improvements
  crates/components/src/input.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
Labels: enhancement 🔥, blocked

#487 feat: Improved node reference listener
  crates/hooks/src/use_node.rs
  crates/state/src/custom_attributes.rs
Labels: enhancement 🔥, blocked

#486 feat: Simplify text measuring and rendering
  crates/components/src/gesture_area.rs
  crates/core/src/layout/skia_measurer.rs
  crates/renderer/src/elements/label.rs
  crates/torin/benches/bench.rs
  crates/torin/examples/demo.rs
  crates/torin/src/custom_measurer.rs
  crates/torin/src/measure.rs
  crates/torin/src/test_utils.rs
Labels: enhancement 🔥, blocked, layout 📐

#392 feat: Support reading platform information in `use_platform`
  crates/hooks/src/use_platform.rs
  crates/hooks/tests/use_platform.rs
  crates/renderer/Cargo.toml
  crates/renderer/src/app.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/window_size.rs
Labels: enhancement 🔥, blocked

#478 feat: `VirtualScrollView` simplification
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/devtools/src/tabs/tree.rs
  examples/cloned_editor.rs
  examples/virtual_scroll_view.rs
Labels: enhancement 🔥, blocked

#505 feat: `static_bytes_to_data`
  crates/elements/src/definitions.rs
  crates/freya/src/lib.rs
  crates/renderer/src/elements/image.rs
  crates/renderer/src/elements/svg.rs
  crates/state/src/custom_attributes.rs
  crates/state/src/style.rs
  examples/image.rs
  examples/opacity.rs
  examples/svg.rs
Labels: enhancement 🔥

#503 feat: Revamp of `use_animation`
  crates/components/src/accordion.rs
  crates/components/src/switch.rs
  crates/freya/src/_docs/animating.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/animation.rs
  crates/hooks/src/lib.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_animation_transition.rs
  crates/hooks/tests/use_animation.rs
  crates/hooks/tests/use_animation_transition.rs
  examples/animation.rs
  examples/performance_overlay_plugin.rs
  examples/progress_bar.rs
  examples/transition.rs
Labels: enhancement 🔥

#418 feat: Skia-safe v0.70
  Cargo.toml
  crates/engine/src/mocked.rs
  crates/renderer/src/app.rs
  crates/renderer/src/elements/svg.rs
  crates/renderer/src/renderer.rs
Labels: skia 🖌️, dependencies

#515 feat: Mutable FontCollection on use_canvas
  crates/components/src/graph.rs
  crates/engine/src/mocked.rs
  crates/renderer/src/elements/rect.rs
  crates/state/src/custom_attributes.rs
Labels: enhancement 🔥

#509 fix: Order colateral events by their layer
  crates/core/src/events/dom_events.rs
  crates/core/src/events/elements_state.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/freya_events.rs
  crates/core/src/events/mod.rs
  crates/core/src/events/potential_event.rs
  crates/core/src/types.rs
  crates/renderer/src/app.rs
Labels: fix 🩹

#514 feat: Bump Dioxus and clean up dependencies
  Cargo.toml
  crates/common/Cargo.toml
  crates/components/Cargo.toml
  crates/core/Cargo.toml
  crates/devtools/Cargo.toml
  crates/dom/Cargo.toml
  crates/elements/Cargo.toml
  crates/freya/Cargo.toml
  crates/hooks/Cargo.toml
  crates/renderer/Cargo.toml
  crates/state/Cargo.toml
  crates/testing/Cargo.toml
  crates/torin/Cargo.toml
Labels: enhancement 🔥, internal impovement👍

#512 feat: Testing improvements
  crates/components/src/accordion.rs
  crates/components/src/button.rs
  crates/components/src/cursor_area.rs
  crates/components/src/dropdown.rs
  crates/components/src/input.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/core/src/events/event_name.rs
  crates/dom/src/dom_adapter.rs
  crates/elements/src/events.rs
  crates/hooks/tests/use_animation.rs
  crates/hooks/tests/use_editable.rs
  crates/renderer/src/event_loop.rs
  crates/state/tests/corner_radius.rs
  crates/state/tests/parse_decoration.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
  crates/testing/src/test_node.rs
  crates/testing/src/test_utils.rs
  crates/testing/tests/test.rs
  crates/torin/benches/bench.rs
  crates/torin/examples/demo.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/test_utils.rs
  crates/torin/tests/other.rs
  crates/torin/tests/root_candidate_resolution.rs
  examples/cursor_area.rs
Labels: enhancement 🔥

#411 feat: Add `Link` component back
  crates/components/Cargo.toml
  crates/components/src/external_link.rs
  crates/components/src/lib.rs
  crates/components/src/link.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  crates/testing/src/test_handler.rs
  examples/external_link.rs
  examples/link.rs
Labels: enhancement 🔥

#513 feat: `Sidebar` component
  crates/components/src/lib.rs
  crates/components/src/sidebar.rs
  crates/core/src/events/event_name.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  examples/router.rs
  examples/sidebar.rs
Labels: enhancement 🔥

#528 chore: Fix spelling mistakes
  crates/core/src/events/event_name.rs
  crates/core/src/events/events_measurer.rs
Labels: documentation
