Repository marc2332/freya, pull requests merged in 2024-01, with the labels that each got.

#449 docs: Book enhancements and FAQ
  book/src/SUMMARY.md
  book/src/differences_with_dioxus.md
  book/src/faq.md
  book/src/what_is_freya.md
Labels: documentation, enhancement 🔥

#455 chore: Clean up internal code
  crates/core/Cargo.toml
  crates/core/src/types.rs
  crates/freya/src/launch.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/window.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: internal impovement👍

#453 feat: Text Editor improvements
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
Labels: enhancement 🔥

#460 fix: Prevent cursor to jump to the next line when there are no more lines, in `TextEditor`
  crates/hooks/src/text_editor.rs
Labels: fix 🩹

#456 feat: Slider improvements
  crates/components/src/slider.rs
  crates/torin/src/torin.rs
  examples/canvas.rs
  examples/editor.rs
  examples/opacity.rs
  examples/progress_bar.rs
  examples/text.rs
Labels: enhancement 🔥

#436 feat: Improved focus integration
  crates/components/src/button.rs
  crates/components/src/switch.rs
  crates/core/src/accessibility/accessibility_provider.rs
  crates/core/src/lib.rs
  crates/core/src/navigation_mode.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_focus.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/canvas.rs
  examples/progress_bar.rs
Labels: enhancement 🔥

#458 chore: Update winit and accesskit
  Cargo.toml
  crates/components/src/accordion.rs
  crates/components/src/button.rs
  crates/components/src/dropdown.rs
  crates/components/src/input.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/core/src/accessibility/accessibility_provider.rs
  crates/core/src/accessibility/accessibility_state.rs
  crates/core/src/types.rs
  crates/devtools/src/lib.rs
  crates/dom/src/dom.rs
  crates/elements/src/events/keyboard.rs
  crates/freya/src/launch.rs
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_focus.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/window.rs
  crates/state/src/custom_attributes.rs
  crates/state/src/values/accessibility.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥

#481 chore: Remove unnecessary mask flags on some node states
  crates/state/src/layout.rs
  crates/state/src/transform.rs
Labels: internal impovement👍

#475 chore: Move Accessibility node state
  crates/state/src/accessibility.rs
  crates/state/src/lib.rs
  crates/state/src/values/mod.rs
Labels: internal impovement👍

#484 chore: Simplify accessibility integration
  crates/core/src/accessibility/accessibility_manager.rs
  crates/core/src/accessibility/accessibility_provider.rs
  crates/core/src/accessibility/accessibility_state.rs
  crates/core/src/accessibility/mod.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: internal impovement👍

#459 feat: Partial IME Support
  crates/components/src/input.rs
  crates/hooks/src/text_editor.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/window.rs
Labels: enhancement 🔥, accessibility 🦾

#476 feat: Support individual vertical gaps but shared horizontal gaps
  book/src/guides/layout.md
  crates/elements/src/_docs/attributes/margin.md
  crates/elements/src/_docs/attributes/padding.md
  crates/state/src/values/gaps.rs
  crates/state/tests/parse_gaps.rs
  examples/paddings.rs
Labels: enhancement 🔥

#467 Remove outdated info from theming docs
  crates/freya/src/_docs/theming.rs
Labels: documentation
