Repository marc2332/freya, pull requests merged in 2024-12, with the labels that each got.

#1012 fix: Update the `use_editable` tests to match github ci
  crates/hooks/tests/use_editable.rs
Labels: fix 🩹

#1015 fix: Handle reordedering of keyed children
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/layout.rs
  crates/core/tests/nodes_reorder.rs
  crates/native-core/src/dioxus.rs
  crates/native-core/src/tree.rs
  crates/torin/src/measure.rs
  crates/torin/src/torin.rs
  crates/torin/tests/other.rs
Labels: fix 🩹

#997 Clock example
  examples/clock.rs
Labels: documentation

#1013 feat: New `AnimatedPosition` component
  crates/components/src/animated_position.rs
  crates/components/src/drag_drop.rs
  crates/components/src/lib.rs
  crates/core/src/render/compositor.rs
  crates/elements/src/_docs/attributes/position.md
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_node.rs
  crates/state/src/values/position.rs
  crates/torin/src/measure.rs
  crates/torin/src/node.rs
  crates/torin/src/values/position.rs
  crates/torin/tests/position.rs
  examples/animated_position.rs
  examples/drag_drop.rs
Labels: enhancement 🔥

#752 feat: `ResizableContainer`
  crates/components/src/lib.rs
  crates/components/src/resizable_container.rs
  crates/devtools/src/lib.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  examples/resizable_container.rs
Labels: enhancement 🔥

#788 feat: Prepare New Docs
  .github/workflows/deploy_docs.yml
  .github/workflows/rust.yml
  Cargo.toml
  book/src/SUMMARY.md
  book/src/guides/devtools.md
  crates/components/src/image.rs
  crates/components/src/svg.rs
  crates/components/src/tabs.rs
  crates/core/src/elements/utils.rs
  crates/freya/Cargo.toml
  crates/freya/src/_docs/accessibility.rs
  crates/freya/src/_docs/async_tasks.rs
  crates/freya/src/_docs/components_and_props.rs
  crates/freya/src/_docs/development_setup.rs
  crates/freya/src/_docs/dioxus_fundamentals.rs
  crates/freya/src/_docs/elements.rs
  crates/freya/src/_docs/en-US.ftl
  crates/freya/src/_docs/es-ES.ftl
  crates/freya/src/_docs/ferris.svg
  crates/freya/src/_docs/hooks.rs
  crates/freya/src/_docs/hot_reload.rs
  crates/freya/src/_docs/i18n.rs
  crates/freya/src/_docs/introduction.rs
  crates/freya/src/_docs/mod.rs
  crates/freya/src/_docs/performance.rs
  crates/freya/src/_docs/router.rs
  crates/freya/src/_docs/router/animated_transitions.rs
  crates/freya/src/_docs/router/native_router.rs
  crates/freya/src/_docs/rust_logo.png
  crates/freya/src/_docs/state_management.rs
  crates/freya/src/_docs/state_management/context.rs
  crates/freya/src/_docs/state_management/global_signals.rs
  crates/freya/src/_docs/state_management/lifecycle.rs
  crates/freya/src/_docs/state_management/memoization.rs
  crates/freya/src/_docs/state_management/signals.rs
  crates/freya/src/_docs/theming.rs
  crates/freya/src/_docs/third_party_state.rs
  crates/freya/src/_docs/ui.rs
  crates/freya/src/lib.rs
Labels: documentation, enhancement 🔥

#1023 fix: Proper `OverflowedContent` animation test
  crates/components/src/overflowed_content.rs
Labels: fix 🩹, ci-cd 🤖

#1022 fix(torin): Also adjust post-layout area in double phase measurements
  crates/torin/src/measure.rs
  crates/torin/tests/flex.rs
Labels: fix 🩹, layout 📐

#1024 release: Release 0.3.0-rc.0
  Cargo.toml
  crates/common/Cargo.toml
  crates/components/Cargo.toml
  crates/core/Cargo.toml
  crates/devtools/Cargo.toml
  crates/elements/Cargo.toml
  crates/engine/Cargo.toml
  crates/freya/Cargo.toml
  crates/hooks/Cargo.toml
  crates/native-core-macro/Cargo.toml
  crates/native-core/Cargo.toml
  crates/renderer/Cargo.toml
  crates/state/Cargo.toml
  crates/testing/Cargo.toml
  crates/torin/Cargo.toml
Labels: release 📆
