Repository marc2332/freya, pull requests merged in 2024-06, with the labels that each got.

#622 feat: Improved special text editing support
  crates/components/src/input.rs
  crates/engine/src/skia.rs
  crates/hooks/src/editor_history.rs
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_editable.rs
  crates/testing/src/launch.rs
  examples/cloned_editor.rs
  examples/simple_editor.rs
Labels: enhancement 🔥

#624 fix: Fix performance dropping rapidly after selecting a text for some time
  crates/core/src/dom/doms.rs
  crates/core/src/dom/paragraph_utils.rs
  crates/hooks/src/use_editable.rs
  examples/simple_editor.rs
Labels: fix 🩹, performance ⚡️

#640 feat: Delete text selection with backspace
  crates/hooks/src/text_editor.rs
  crates/hooks/tests/use_editable.rs
Labels: enhancement 🔥

#642 feat: Text dragging with shift and cursor
  crates/components/src/input.rs
  crates/hooks/src/use_editable.rs
  examples/floating_editors.rs
  examples/simple_editor.rs
Labels: enhancement 🔥

#644 feat: Remove text with Delete
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
Labels: enhancement 🔥

#631 feat: `use_preferred_theme`
  crates/components/src/lib.rs
  crates/components/src/native_container.rs
  crates/components/src/theme.rs
  crates/core/src/lib.rs
  crates/core/src/navigation_mode.rs
  crates/core/src/platform_state.rs
  crates/core/src/types.rs
  crates/devtools/src/lib.rs
  crates/freya/src/launch.rs
  crates/freya/src/lib.rs
  crates/hooks/src/lib.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/src/use_preferred_theme.rs
  crates/hooks/src/use_theme.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/app_dog.rs
  examples/cloned_editor.rs
  examples/floating_editors.rs
  examples/menu.rs
  examples/popup.rs
  examples/preferred_theme.rs
  examples/text.rs
Labels: enhancement 🔥

#635 feat: Reactive Platform data
  crates/core/src/platform_state.rs
  crates/hooks/src/lib.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/src/use_platform.rs
  crates/hooks/src/use_platform_information.rs
  crates/hooks/tests/use_platform_information.rs
  crates/renderer/src/app.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/preferred_theme.rs
  examples/window_size.rs
Labels: enhancement 🔥

#637 feat: Reactive Window data
  crates/core/src/platform_state.rs
  crates/renderer/src/app.rs
  crates/testing/src/launch.rs
  examples/window_fullscreen.rs
  examples/window_fullscreen_min_max.rs
  examples/window_size.rs
Labels: enhancement 🔥

#638 docs: Update the differences with Dioxus doc
  book/src/differences_with_dioxus.md
  book/src/faq.md
Labels: enhancement 🔥

#639 docs: Update the book guides
  book/src/dioxus.md
  book/src/getting_started.md
Labels: enhancement 🔥

#648 fix: Proper accessibility reactivity
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/core/src/platform_state.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/tests/use_focus.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
Labels: enhancement 🔥, fix 🩹

#647 feat: Revamp internal text selection
  crates/common/src/event_messages.rs
  crates/common/src/paragraphs.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/paragraph_utils.rs
  crates/core/src/layout/layout_measurer.rs
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  crates/state/src/custom_attributes.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, fix 🩹, performance ⚡️

#650 feat: Queued focus
  crates/common/src/event_messages.rs
  crates/hooks/src/use_focus.rs
  crates/renderer/src/app.rs
  crates/renderer/src/event_loop.rs
  examples/floating_editors.rs
Labels: enhancement 🔥

#652 feat: Select all text
  crates/hooks/src/text_editor.rs
  crates/hooks/tests/use_editable.rs
Labels: enhancement 🔥

#653 refactor: Use single position cursor
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_editable.rs
  examples/floating_editors.rs
  examples/simple_editor.rs
Labels: internal impovement👍

#629 refactor: process all queued keyboard events at once
  crates/core/src/events/events_measurer.rs
  crates/core/src/types.rs
  crates/renderer/src/app.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, experiment 🧪

#601 feat: `onpress` event for `Button`
  crates/components/src/button.rs
  crates/components/src/hooks/use_form.rs
  crates/components/src/menu.rs
  crates/components/src/popup.rs
  crates/components/src/snackbar.rs
  crates/components/src/switch.rs
  crates/elements/src/events/pointer.rs
  crates/freya/src/_docs/theming.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/tests/use_asset_cacher.rs
  examples/accessibility.rs
  examples/app_dog.rs
  examples/counter.rs
  examples/dynamic_theme.rs
  examples/floating_editors.rs
  examples/i18n.rs
  examples/menu.rs
  examples/password.rs
  examples/popup.rs
  examples/progress_bar.rs
  examples/push_remove.rs
  examples/snackbar.rs
  examples/text.rs
  examples/window_fullscreen_min_max.rs
  examples/window_title.rs
Labels: enhancement 🔥, breaking

#682 chore: Run against main branch of Dioxus every 3 days
  .github/workflows/dioxus_rust.yml
  patches/dioxus_main_branch.patch
Labels: enhancement 🔥, ci-cd 🤖

#657 feat: Persisted devtools routing
  crates/devtools/src/lib.rs
  crates/devtools/src/node.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
Labels: enhancement 🔥

#669 feat: Do not re-export freya-testing
  crates/freya/Cargo.toml
Labels: enhancement 🔥

#672 feat: Persist devtools node inspector routing
  crates/devtools/src/lib.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
Labels: enhancement 🔥

#667 feat: More reliable devtools
  crates/devtools/Cargo.toml
  crates/devtools/src/hooks/mod.rs
  crates/devtools/src/hooks/use_node_info.rs
  crates/devtools/src/hooks/use_selected_node.rs
  crates/devtools/src/lib.rs
  crates/devtools/src/node.rs
  crates/devtools/src/state.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
  crates/freya/src/launch.rs
  crates/renderer/src/app.rs
  crates/renderer/src/devtools.rs
  crates/renderer/src/lib.rs
Labels: enhancement 🔥, performance ⚡️

#675 feat: Support nested routes in `ActivableRoute`
  crates/components/src/activable_route.rs
  examples/router.rs
Labels: enhancement 🔥

#673 feat: Tab and Tabsbar components
  crates/components/src/lib.rs
  crates/components/src/tabs.rs
  crates/devtools/src/lib.rs
  crates/devtools/src/tab.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  examples/tab.rs
Labels: enhancement 🔥

#681 feat: Tree builder utilities for components
  Cargo.toml
  crates/components/src/lib.rs
  crates/components/src/tree.rs
  examples/file_explorer.rs
Labels: enhancement 🔥

#668 fix: Store cached assets in Root Scope
  crates/hooks/src/use_asset_cacher.rs
  crates/hooks/src/use_init_native_platform.rs
Labels: fix 🩹

#664 feat: Optionally allow inserting tabs as spaces
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  examples/simple_editor.rs
Labels: enhancement 🔥

#678 feat: Replace selected text with the new insert
  crates/hooks/src/text_editor.rs
  crates/hooks/tests/use_editable.rs
Labels: enhancement 🔥

#684 feat: Tree-like explorer for devtools
  crates/devtools/src/lib.rs
  crates/devtools/src/node.rs
  crates/devtools/src/state.rs
  crates/devtools/src/tabs/tree.rs
  crates/renderer/src/devtools.rs
Labels: enhancement 🔥

#598 feat: `winit` v0.30.0 + `glutin-winit` v0.5.0 + `accesskit` v0.14.0 + `accesskit_winit` v0.20.0
  Cargo.toml
  crates/common/src/event_messages.rs
  crates/core/src/accessibility/accessibility_manager.rs
  crates/freya/src/launch.rs
  crates/hooks/tests/use_editable.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/config.rs
  crates/renderer/src/event_loop.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/render.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window.rs
  examples/cloned_editor.rs
  examples/custom_font.rs
  examples/frameless_window.rs
  examples/installer/src/main.rs
  examples/launch_setup.rs
  examples/mouse_trace.rs
  examples/performance_overlay_plugin.rs
  examples/plugin.rs
  examples/stateful_window.rs
  examples/window_icon.rs
Labels: enhancement 🔥, dependencies, internal impovement👍

#606 feat: React to scale factor changes
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/layout/layout_measurer.rs
  crates/core/src/layout/skia_measurer.rs
  crates/renderer/src/app.rs
  crates/renderer/src/elements/paragraph.rs
  crates/renderer/src/elements/rect.rs
  crates/renderer/src/render.rs
  crates/state/src/font_style.rs
  crates/state/src/layout.rs
  crates/state/src/style.rs
  crates/torin/src/node.rs
  crates/torin/src/values/position.rs
Labels: enhancement 🔥

#607 feat: Expose scale factor
  crates/components/src/graph.rs
  crates/core/src/platform_state.rs
  crates/hooks/src/use_canvas.rs
  crates/renderer/src/app.rs
  crates/renderer/src/elements/rect.rs
  crates/renderer/src/renderer.rs
  crates/state/src/custom_attributes.rs
  crates/testing/src/launch.rs
  examples/render_canvas.rs
  examples/shader.rs
Labels: enhancement 🔥

#693 feat: Signal-based reactivity for `use_canvas`
  crates/components/src/graph.rs
  crates/hooks/src/use_canvas.rs
  examples/render_canvas.rs
  examples/shader.rs
Labels: enhancement 🔥

#694 chore: Fix the color value in the launch method doc test
  crates/freya/src/launch.rs
Labels: documentation, fix 🩹

#696 fix: Fix some inconsitencies with the winit 0.30 update
  crates/renderer/src/config.rs
  crates/renderer/src/renderer.rs
  examples/launch_setup.rs
Labels: fix 🩹

#701 feat: Built-in vertical alignment for text
  crates/core/src/dom/paragraph_utils.rs
  crates/core/src/layout/skia_measurer.rs
  crates/elements/src/definitions.rs
  crates/renderer/src/elements/label.rs
  crates/renderer/src/elements/paragraph.rs
  crates/renderer/src/render.rs
  examples/cloned_editor.rs
  examples/floating_editors.rs
  examples/simple_editor.rs
Labels: enhancement 🔥

#704 feat: `highlight_mode` attribute
  crates/core/src/dom/paragraph_utils.rs
  crates/core/src/layout/skia_measurer.rs
  crates/elements/src/definitions.rs
  crates/native-core/src/attributes.rs
  crates/renderer/src/elements/label.rs
  crates/renderer/src/elements/paragraph.rs
  crates/state/src/cursor.rs
  crates/state/src/values/highlight.rs
  crates/state/src/values/mod.rs
  crates/state/tests/parse_highlight.rs
  examples/cloned_editor.rs
Labels: enhancement 🔥

#706 fix: Prevent crash on keyboard navigation with empty text
  crates/hooks/src/text_editor.rs
  crates/hooks/tests/use_editable.rs
Labels: fix 🩹

#705 feat: Only send keydowns when the window is focused
  crates/renderer/src/renderer.rs
Labels: enhancement 🔥

#710 chore: Rust 1.79
  crates/state/src/values/color.rs
  rust-toolchain.toml
Labels: internal impovement👍

#713 refactor: Rename node states to follow an unified naming
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/node.rs
  crates/core/src/skia/paragraph.rs
  crates/core/src/skia/skia_measurer.rs
  crates/core/src/skia/skia_renderer/image.rs
  crates/core/src/skia/skia_renderer/paragraph.rs
  crates/core/src/skia/skia_renderer/rect.rs
  crates/core/src/skia/skia_renderer/renderer.rs
  crates/core/src/skia/skia_renderer/svg.rs
  crates/state/src/cursor.rs
  crates/state/src/font_style.rs
  crates/state/src/references.rs
  crates/state/src/style.rs
  crates/state/src/transform.rs
  crates/testing/src/test_node.rs
Labels: internal impovement👍

#715 refactor: Reorganize `freya-renderer`
  crates/core/src/layout.rs
  crates/renderer/src/config.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window_state.rs
  crates/renderer/src/winit_waker.rs
Labels: internal impovement👍

#716 feat: Skia-safe v0.75
  Cargo.toml
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/renderer/src/window_state.rs
Labels: internal impovement👍

#661 feat: Use System fonts
  crates/components/src/button.rs
  crates/core/src/lib.rs
  crates/core/src/style.rs
  crates/elements/src/definitions.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/tests/use_editable.rs
  crates/renderer/src/app.rs
  crates/renderer/src/config.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥

#729 internal: Simplify the `VirtualDOM` polling
  crates/common/src/event_messages.rs
  crates/renderer/src/app.rs
  crates/testing/src/test_handler.rs
Labels: internal impovement👍

#731 Internal: Rethink mutations writer
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/layout.rs
  crates/core/src/platform_state.rs
  crates/core/src/skia/paragraph.rs
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window_state.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: internal impovement👍

#720 feat: Canvas snapshots for `freya-testing`
  .gitignore
  Cargo.toml
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  examples/canvas_snapshot.rs
Labels: enhancement 🔥

#723 feat: Render one more item in VirtualScrollView for smooth scrolling
  crates/components/src/scroll_views/virtual_scroll_view.rs
Labels: enhancement 🔥

#737 feat: `dioxus-query` example
  Cargo.toml
  examples/dioxus_query.rs
Labels: documentation, enhancement 🔥

#744 fix: Skip DOM Nodes loaded in the same mutations run
  crates/core/src/dom/mutations_writer.rs
Labels: fix 🩹

#748 feat: Simplify return type of `use_animation`
  crates/hooks/src/use_animation.rs
Labels: enhancement 🔥

#745 feat: Animated router transitions
  crates/components/src/animated_router.rs
  crates/components/src/lib.rs
  examples/animated_sidebar.rs
  examples/animated_tabs.rs
Labels: enhancement 🔥

#747 feat: `BottomTab` component
  crates/components/src/tabs.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  examples/animated_tabs.rs
Labels: enhancement 🔥
