Repository marc2332/freya, pull requests merged in 2024-05, with the labels that each got.

#594 feat: Close popup with esc key
  crates/components/src/popup.rs
Labels: enhancement 🔥

#597 feat: Add window drag area
  crates/common/src/event_messages.rs
  crates/components/src/lib.rs
  crates/components/src/window_drag_area.rs
  crates/hooks/src/use_platform.rs
  crates/renderer/src/event_loop.rs
  examples/window_drag_area.rs
Labels: enhancement 🔥

#600 chore: Rust 1.78
  .github/workflows/benchmarks.yml
  crates/common/src/event_messages.rs
  crates/components/src/dropdown.rs
  crates/components/src/window_drag_area.rs
  crates/native-core/src/tags.rs
  rust-toolchain.toml
Labels: internal impovement👍

#613 feat: Close app with `use_platform`
  crates/common/src/event_messages.rs
  crates/hooks/src/use_platform.rs
  crates/renderer/src/event_loop.rs
Labels: enhancement 🔥

#604 feat: Animated `VirtualScrollView`
  crates/components/src/scroll_views/virtual_scroll_view.rs
Labels: enhancement 🔥

#609 fix: Out of sync element ids on events
  crates/core/src/events/dom_event.rs
  crates/core/src/events/events_measurer.rs
  crates/renderer/src/app.rs
  crates/testing/src/test_handler.rs
Labels: fix 🩹

#627 feat: `min/max/fullscreen window` in `use_platform`.
  crates/hooks/src/use_platform.rs
  examples/window_fullscreen.rs
  examples/window_min_max.rs
Labels: enhancement 🔥

#625 fix: `WindowDragArea` component hanging on non-left click.
  crates/components/src/window_drag_area.rs
Labels: fix 🩹

#626 feat: `WithWindow` event
  crates/common/src/event_messages.rs
  crates/components/src/graph.rs
  crates/hooks/src/use_platform.rs
  crates/renderer/src/event_loop.rs
  examples/window_fullscreen.rs
  examples/window_min_max.rs
  examples/window_title.rs
Labels: enhancement 🔥
