Repository marc2332/freya, pull requests merged in 2024-09, with the labels that each got.

#834 feat: `spacing` attribute
  crates/components/src/dropdown.rs
  crates/components/src/link.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/sidebar.rs
  crates/components/src/switch.rs
  crates/core/src/dom/dom_adapter.rs
  crates/elements/src/_docs/attributes/spacing.md
  crates/elements/src/definitions.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  crates/native-core/src/attributes.rs
  crates/state/src/layout.rs
  crates/torin/src/measure.rs
  crates/torin/src/node.rs
  crates/torin/tests/spacing.rs
  examples/counter.rs
  examples/popup.rs
  examples/spacing.rs
Labels: enhancement 🔥, layout 📐

#839 feat: website example
  Cargo.toml
  crates/components/src/link.rs
  crates/components/src/svg.rs
  examples/freya_icon.svg
  examples/freya_logo.svg
  examples/website.rs
Labels: documentation, enhancement 🔥

#842 fix: Use individual methods to set decoration
  crates/engine/src/mocked.rs
  crates/state/src/font_style.rs
Labels: fix 🩹

#846 docs: Documents editor example
  .gitignore
  crates/elements/src/_docs/attributes/main_align_cross_align.md
  examples/documents_editor.rs
Labels: documentation

#811 feat: Incremental rendering
  .vscode/settings.json
  Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/compositor_dirty_nodes.rs
  crates/common/src/layers.rs
  crates/common/src/layout.rs
  crates/common/src/lib.rs
  crates/common/src/paragraphs.rs
  crates/components/src/graph.rs
  crates/components/src/slider.rs
  crates/core/Cargo.toml
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/elements/label.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/elements/rect.rs
  crates/core/src/elements/utils.rs
  crates/core/src/event_messages.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/layout.rs
  crates/core/src/lib.rs
  crates/core/src/render.rs
  crates/core/src/render/compositor.rs
  crates/core/src/render/mod.rs
  crates/core/src/render/pipeline.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/render/wireframe_renderer.rs
  crates/core/src/skia/mod.rs
  crates/core/src/skia/skia_renderer.rs
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/freya/Cargo.toml
  crates/freya/src/launch.rs
  crates/hooks/src/use_node.rs
  crates/hooks/src/use_platform.rs
  crates/native-core/src/node.rs
  crates/native-core/src/real_dom.rs
  crates/renderer/src/app.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/size.rs
  crates/renderer/src/window_state.rs
  crates/state/src/cursor.rs
  crates/state/src/font_style.rs
  crates/state/src/layer.rs
  crates/state/src/layout.rs
  crates/state/src/style.rs
  crates/state/src/transform.rs
  crates/state/src/values/border.rs
  crates/testing/src/test_handler.rs
  crates/torin/src/geometry.rs
  crates/torin/src/torin.rs
  examples/floating_editors.rs
  examples/massive.rs
  examples/render_canvas.rs
  examples/shader.rs
  examples/shader_editor.rs
Labels: enhancement 🔥, skia 🖌️, performance ⚡️

#853 feat: Incremental Accessibility Tree
  crates/common/src/accessibility.rs
  crates/common/src/lib.rs
  crates/core/src/accessibility/accessibility_manager.rs
  crates/core/src/accessibility/mod.rs
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/layout.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
  crates/state/src/accessibility.rs
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, accessibility 🦾

#822 feat: Graphics Drivers
  crates/renderer/src/drivers/gl.rs
  crates/renderer/src/drivers/mod.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window_state.rs
Labels: enhancement 🔥, internal impovement👍

#848 feat: Nicer Switch
  crates/components/src/switch.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/use_animation.rs
  examples/switch_theme.rs
Labels: enhancement 🔥

#856 feat: Refreshed theme colors
  crates/components/src/progress_bar.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  examples/switch_theme.rs
Labels: enhancement 🔥

#864 feat: Testing events utils
  crates/components/src/accordion.rs
  crates/components/src/button.rs
  crates/components/src/checkbox.rs
  crates/components/src/cursor_area.rs
  crates/components/src/drag_drop.rs
  crates/components/src/dropdown.rs
  crates/components/src/link.rs
  crates/components/src/menu.rs
  crates/components/src/native_router.rs
  crates/components/src/popup.rs
  crates/components/src/radio.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/use_scroll_controller.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/snackbar.rs
  crates/components/src/switch.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/render/compositor.rs
  crates/core/tests/event_bubbling.rs
  crates/core/tests/pointer_events.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/tests/use_animation.rs
  crates/hooks/tests/use_asset_cacher.rs
  crates/hooks/tests/use_editable.rs
  crates/hooks/tests/use_focus.rs
  crates/native-core/src/events.rs
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
  crates/testing/src/test_handler.rs
  crates/testing/tests/test.rs
  examples/canvas_snapshot.rs
Labels: enhancement 🔥

#855 feat: infer accesskit properties from node state
  crates/core/src/accessibility/tree.rs
  crates/engine/src/mocked.rs
Labels: enhancement 🔥, accessibility 🦾

#838 feat: Calc operator precedence
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥

#858 feat: Ergonomic improvements in ScrollView
  crates/components/src/scroll_views/mod.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/sidebar.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  examples/accordion.rs
  examples/cloned_editor.rs
  examples/controlled_scroll.rs
  examples/material_design_app.rs
  examples/paragraph.rs
  examples/scroll.rs
  examples/simple_editor.rs
  examples/ui.rs
Labels: enhancement 🔥

#865 feat: Rename `mouseover` to `mousemove`
  crates/components/src/cursor_area.rs
  crates/components/src/drag_drop.rs
  crates/components/src/input.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/core/src/events/events_measurer.rs
  crates/core/tests/pointer_events.rs
  crates/elements/src/_docs/events/globalmousemove.md
  crates/elements/src/_docs/events/mousemove.md
  crates/elements/src/definitions.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_editable.rs
  crates/native-core/src/events.rs
  crates/renderer/src/renderer.rs
  crates/testing/src/test_handler.rs
  examples/cloned_editor.rs
  examples/documents_editor.rs
  examples/drag.rs
  examples/floating_editors.rs
  examples/gamepad_trace.rs
  examples/mouse.rs
  examples/mouse_trace.rs
  examples/shader_editor.rs
  examples/simple_editor.rs
  examples/ui.rs
Labels: enhancement 🔥

#867 feat: Optional uncontrolled accessibility IDs
  crates/common/src/accessibility.rs
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/doms.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/renderer/src/app.rs
  crates/state/Cargo.toml
  crates/state/src/accessibility.rs
  crates/testing/src/test_handler.rs
  examples/focus.rs
  examples/keyboard_navigation.rs
Labels: enhancement 🔥

#868 fix: Proper drop of unused assets in asset cacher
  crates/hooks/src/use_asset_cacher.rs
Labels: fix 🩹

#869 feat: Rename a11y attributes
  crates/components/src/button.rs
  crates/components/src/dropdown.rs
  crates/components/src/input.rs
  crates/components/src/menu.rs
  crates/components/src/network_image.rs
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/components/src/tabs.rs
  crates/components/src/tile.rs
  crates/core/src/accessibility/mod.rs
  crates/core/src/accessibility/tree.rs
  crates/elements/src/definitions.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/tests/use_focus.rs
  crates/native-core/src/attributes.rs
  crates/state/src/accessibility.rs
  examples/accessibility.rs
  examples/floating_editors.rs
Labels: enhancement 🔥

#873 fix(torin): Ignore absolute nodes for spacing and alignments
  crates/torin/src/measure.rs
  crates/torin/src/node.rs
  crates/torin/tests/alignment.rs
Labels: fix 🩹, layout 📐

#879 fix: Proper incremental redraws for elements with outer or center borders
  crates/core/src/elements/rect.rs
  crates/core/src/render/compositor.rs
  crates/torin/src/geometry.rs
Labels: fix 🩹

#880 fix: Proper support for keyboard navigation for Radio
  crates/components/src/radio.rs
  crates/components/src/tile.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
Labels: enhancement 🔥

#888 fix: Dont trigger mouse enter on touch move
  crates/native-core/src/events.rs
Labels: fix 🩹

#890 fix: Use collateral event to check if event is allowed
  crates/components/src/button.rs
  crates/components/src/native_router.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/nodes_state.rs
  crates/native-core/src/events.rs
Labels: fix 🩹

#894 fix: Properly adjust accumulated sizes when using padding
  crates/torin/src/measure.rs
Labels: fix 🩹

#896 fix: Filter enter events properly, regression of #895
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/nodes_state.rs
  crates/core/tests/pointer_events.rs
Labels: fix 🩹

#884 feat: Only focus focusable nodes
  crates/components/src/button.rs
  crates/components/src/input.rs
  crates/components/src/menu.rs
  crates/components/src/radio.rs
  crates/components/src/tabs.rs
  crates/core/src/accessibility/tree.rs
  crates/elements/src/definitions.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/native-core/src/attributes.rs
  crates/state/src/accessibility.rs
  crates/state/src/values/focusable.rs
  crates/state/src/values/mod.rs
  crates/state/tests/parse_focusable.rs
Labels: enhancement 🔥

#897 feat: Rename `pointerover` event to `pointermove`
  crates/core/tests/pointer_events.rs
  crates/elements/src/_docs/events/pointermove.md
  crates/elements/src/definitions.rs
  crates/native-core/src/events.rs
  examples/pointer.rs
Labels: enhancement 🔥

#911 Add NixOS setup
  book/src/setup.md
Labels: documentation

#912 fix: Scale with window's scaled actor the areas requested for invalid…
  crates/renderer/src/renderer.rs
Labels: fix 🩹

#900 feat: `TooltipContainer`
  crates/components/src/link.rs
  crates/components/src/tooltip.rs
  crates/core/src/render/skia_measurer.rs
  examples/switch_theme.rs
  examples/tooltip.rs
Labels: enhancement 🔥

#901 fix: Various fixes when editing utf16-encoded text
  crates/components/src/input.rs
  crates/hooks/src/editor_history.rs
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_editable.rs
  examples/cloned_editor.rs
  examples/documents_editor.rs
  examples/shader_editor.rs
  examples/simple_editor.rs
Labels: fix 🩹

#899 feat: `import_image`
  crates/components/src/image.rs
  crates/components/src/lib.rs
  examples/import_image.rs
Labels: enhancement 🔥

#907 feat: Support RootPercentage in `calc()`
  crates/state/src/values/size.rs
  crates/state/tests/parse_size.rs
  crates/torin/src/values/size.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥

#921 fix: linear gradient angles
  crates/state/src/values/gradient.rs
Labels: fix 🩹

#919 optimization: Avoid marking as dirty fixed-size nodes with non-start alignments or layout references if they haven't actually been modified
  crates/torin/src/measure.rs
  crates/torin/src/node.rs
  crates/torin/src/torin.rs
Labels: performance ⚡️

#923 feat: Deterministic order of rendering
  crates/core/src/render/pipeline.rs
Labels: enhancement 🔥

#927 fix: Clamp progress bar progress
  crates/components/src/progress_bar.rs
Labels: fix 🩹

#910 feat: Vertical `direction` for `Slider`
  crates/components/src/slider.rs
  examples/floating_editors.rs
  examples/opacity.rs
  examples/opengl_rtt.rs
  examples/progress_bar.rs
  examples/switch_theme.rs
  examples/text.rs
Labels: enhancement 🔥

#928 feat: Ajust the custom layers of some built-in-components
  crates/components/src/dropdown.rs
  crates/components/src/popup.rs
  crates/components/src/snackbar.rs
  crates/components/src/tooltip.rs
Labels: enhancement 🔥

#930 refactor: Remove `accesskit` window rendering workaround
  crates/renderer/src/window_state.rs
Labels: internal impovement👍

#933 feat: Add `UseEditable::new_in_hook` for manual creation of editable content
  Cargo.toml
  crates/hooks/src/use_editable.rs
  examples/text_editors.rs
Labels: enhancement 🔥

#931 feat: Custom scale factor shortcuts
  Cargo.toml
  crates/freya/Cargo.toml
  crates/renderer/Cargo.toml
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
Labels: enhancement 🔥

#934 fix: Layout references not triggering
  crates/core/src/render/skia_measurer.rs
  crates/torin/src/custom_measurer.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/measure.rs
  crates/torin/src/torin.rs
Labels: fix 🩹, performance ⚡️

#932 fix: Use the real text height for layout
  crates/components/src/button.rs
  crates/components/src/tooltip.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/node.rs
  crates/core/src/render/skia_measurer.rs
  crates/devtools/src/tabs/style.rs
  crates/hooks/tests/use_editable.rs
  crates/state/src/font_style.rs
  examples/input.rs
Labels: fix 🩹

#935 feat: `LaunchConfig::with_visible`
  crates/renderer/src/config.rs
  crates/renderer/src/window_state.rs
Labels: enhancement 🔥

#914 feat: Unified colors theming
  crates/components/src/input.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/theming/themes.rs
  crates/hooks/src/use_theme.rs
  examples/switch_theme.rs
  examples/themer.rs
Labels: enhancement 🔥, experiment 🧪

#926 feat: Keyboard navigation for `Checkbox`
  crates/components/src/checkbox.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  examples/switch_theme.rs
Labels: enhancement 🔥

#836 feat: per-side border widths
  crates/core/src/elements/rect.rs
  crates/elements/src/_docs/attributes/border.md
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/state/src/values/border.rs
  crates/state/tests/parse_border.rs
  examples/border.rs
Labels: enhancement 🔥

#942 fix: Update the incremental removal of accessible nodes
  crates/core/src/accessibility/tree.rs
Labels: fix 🩹
