Repository marc2332/freya, pull requests merged in 2024-10, with the labels that each got.

#959 fix: Avoid trigering side effects in orphan nodes updates
  crates/state/src/accessibility.rs
  crates/state/src/cursor.rs
  crates/state/src/font_style.rs
  crates/state/src/layer.rs
  crates/state/src/layout.rs
  crates/state/src/transform.rs
Labels: fix 🩹

#944 feat: Event Loop Builder hook
  Cargo.toml
  crates/renderer/src/config.rs
  crates/renderer/src/renderer.rs
  crates/renderer/src/window_state.rs
Labels: enhancement 🔥

#938 feat: Add `FPS` label to the performance overlay plugin
  crates/freya/src/plugins/performance_overlay.rs
Labels: enhancement 🔥

#958 feat: Parent children based accessibility relations
  crates/core/src/accessibility/mod.rs
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/mutations_writer.rs
  crates/state/src/accessibility.rs
Labels: accessibility 🦾, internal impovement👍

#937 refactor: Split core render functions
  crates/core/src/elements/label.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/elements/rect.rs
  crates/core/src/render/mod.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/render/utils/borders.rs
  crates/core/src/render/utils/label.rs
  crates/core/src/render/utils/mod.rs
  crates/core/src/render/utils/paragraph.rs
  crates/core/src/render/utils/shadows.rs
  crates/state/src/values/fill.rs
Labels: internal impovement👍

#952 feat: Button variants
  crates/components/src/button.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/theming/themes.rs
  examples/button.rs
  examples/switch_theme.rs
Labels: enhancement 🔥

#949 feat: Horizontal scroll for `Input`
  crates/components/src/input.rs
  crates/components/src/scroll_views/scroll_view.rs
  examples/input.rs
Labels: enhancement 🔥

#955 refactor: Remove unnecessary border wrappers of Radio and Checkbox
  crates/components/src/checkbox.rs
  crates/components/src/radio.rs
Labels: internal impovement👍

#964 fix: Skip updated but also removed accessibility nodes
  crates/common/src/accessibility.rs
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/mutations_writer.rs
Labels: fix 🩹

#967 fix: Create accesskit adapter before making window visible
  crates/renderer/src/app.rs
  crates/renderer/src/window_state.rs
Labels: fix 🩹

#971 fix: Traverse layout-mutated children with no drawing area in compositor
  crates/core/src/layout.rs
Labels: fix 🩹

#974 chore: Clean up readme
  README.md
Labels: enhancement 🔥

#946 chore: Update readme and contributing
  .github/overview.png
  CONTRIBUTING.md
  README.md
Labels: documentation

#950 refactor: organize inconsistent attributes
  crates/elements/src/definitions.rs
Labels: enhancement 🔥

#976 feat: `text_height` attribute to control the height behavior of text
  crates/components/src/button.rs
  crates/components/src/progress_bar.rs
  crates/core/src/render/utils/label.rs
  crates/core/src/render/utils/paragraph.rs
  crates/elements/src/_docs/attributes/text_height.md
  crates/elements/src/definitions.rs
  crates/engine/src/mocked.rs
  crates/native-core/src/attributes.rs
  crates/state/src/font_style.rs
  crates/state/src/values/mod.rs
  crates/state/src/values/text_height.rs
Labels: enhancement 🔥

#916 docs: Add missing 0.2 docs
  crates/components/src/activable_route.rs
  crates/elements/src/definitions.rs
  crates/hooks/src/use_activable_route.rs
Labels: documentation

#979 feat: in-memory canvas snapshots
  .gitignore
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥

#981 feat: Allow passing state context in freya-testing
  crates/core/src/render/compositor.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/src/use_node.rs
  crates/hooks/tests/use_focus.rs
  crates/hooks/tests/use_platform_information.rs
  crates/testing/src/config.rs
  crates/testing/src/launch.rs
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥

#973 chore: Replace dioxus-sdk with dioxus-clipboard
  Cargo.toml
  crates/components/src/native_container.rs
  crates/components/src/popup.rs
  crates/components/src/slider.rs
  crates/components/src/tile.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  crates/hooks/tests/use_platform_information.rs
  examples/text_editors.rs
Labels: internal impovement👍

#977 feat: `on_deps_change` method for animations
  crates/components/src/switch.rs
  crates/hooks/src/use_animation.rs
Labels: enhancement 🔥

#989 fix: Use the config size for the compositor dirty area in freya-testing when resizing
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: fix 🩹
