Repository marc2332/freya, pull requests merged in 2024-04, with the labels that each got.

#561 fix: Horizontal scrolling with keyboard
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/native-core/src/events.rs
Labels: fix 🩹

#562 fix: Remove paragraph elements
  crates/dom/src/dom.rs
  crates/dom/src/mutations_writer.rs
Labels: fix 🩹

#563 chore: Merge dom and core crates
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/accessibility/accessibility_manager.rs
  crates/core/src/accessibility/mod.rs
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mod.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/dom/paragraph_utils.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/layout/layout_measurer.rs
  crates/core/src/layout/skia_measurer.rs
  crates/core/src/lib.rs
  crates/core/src/node.rs
  crates/core/src/plugins.rs
  crates/core/src/render.rs
  crates/devtools/Cargo.toml
  crates/devtools/src/lib.rs
  crates/dom/Cargo.toml
  crates/dom/src/lib.rs
  crates/freya/Cargo.toml
  crates/freya/src/launch.rs
  crates/renderer/Cargo.toml
  crates/renderer/src/app.rs
  crates/renderer/src/elements/image.rs
  crates/renderer/src/elements/paragraph.rs
  crates/renderer/src/elements/rect.rs
  crates/renderer/src/elements/svg.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/renderer.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  crates/testing/src/test_utils.rs
Labels: enhancement 🔥

#564 fix: Proper state equality checks
  crates/state/src/font_style.rs
  crates/state/src/layout.rs
Labels: fix 🩹

#565 feat: Allow overriding the scrollbar theme from ScrollView
  crates/components/src/scroll_views/mod.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/hooks/src/theming/dark.rs
  crates/hooks/src/theming/light.rs
  crates/hooks/src/theming/mod.rs
  examples/scroll.rs
Labels: enhancement 🔥

#568 fix: Bring back node id layout check
  crates/state/src/layout.rs
Labels: fix 🩹

#569 feat: Performance improvements
  Cargo.toml
  crates/common/src/paragraphs.rs
  crates/components/src/switch.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/plugins.rs
  crates/freya/src/plugins/performance_overlay.rs
  crates/native-core/src/real_dom.rs
  crates/renderer/src/app.rs
  crates/state/src/layout.rs
Labels: enhancement 🔥, performance ⚡️

#544 chore: Bump dx
  Cargo.toml
  README.md
  book/src/what_is_freya.md
  crates/hooks/Cargo.toml
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  crates/hooks/src/use_editable.rs
  examples/i18n.rs
Labels: dioxus🧬, dependencies

#533 feat: Add `use_asset_cacher`
  crates/components/Cargo.toml
  crates/components/src/network_image.rs
  crates/elements/src/definitions.rs
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/freya/src/lib.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/lib.rs
  crates/hooks/src/use_asset_cacher.rs
  crates/hooks/tests/use_asset_cacher.rs
  crates/renderer/src/elements/image.rs
  crates/renderer/src/window.rs
  crates/state/src/custom_attributes.rs
  crates/state/src/style.rs
  examples/image.rs
  examples/opacity.rs
  examples/svg.rs
Labels: enhancement 🔥

#479 feat: `use_form` hook
  crates/components/src/hooks/mod.rs
  crates/components/src/hooks/use_form.rs
  crates/components/src/lib.rs
  examples/form.rs
Labels: enhancement 🔥

#571 chore: Rename native-core crates
  Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/layers.rs
  crates/common/src/paragraphs.rs
  crates/core/Cargo.toml
  crates/core/src/accessibility/mod.rs
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/dom/paragraph_utils.rs
  crates/core/src/events/dom_event.rs
  crates/core/src/events/event_name.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/nodes_state.rs
  crates/core/src/events/potential_event.rs
  crates/core/src/layout/skia_measurer.rs
  crates/core/src/node.rs
  crates/core/src/plugins.rs
  crates/core/src/render.rs
  crates/devtools/Cargo.toml
  crates/devtools/src/hooks/use_selected_node.rs
  crates/devtools/src/lib.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
  crates/native-core-macro/Cargo.toml
  crates/native-core-macro/src/lib.rs
  crates/native-core/Cargo.toml
  crates/native-core/examples/simple.rs
  crates/native-core/tests/passes.rs
  crates/renderer/Cargo.toml
  crates/renderer/src/app.rs
  crates/renderer/src/elements/image.rs
  crates/renderer/src/elements/label.rs
  crates/renderer/src/elements/paragraph.rs
  crates/renderer/src/elements/rect.rs
  crates/renderer/src/elements/svg.rs
  crates/renderer/src/lib.rs
  crates/renderer/src/renderer.rs
  crates/state/Cargo.toml
  crates/state/src/accessibility.rs
  crates/state/src/cursor.rs
  crates/state/src/custom_attributes.rs
  crates/state/src/font_style.rs
  crates/state/src/layer.rs
  crates/state/src/layout.rs
  crates/state/src/references.rs
  crates/state/src/style.rs
  crates/state/src/transform.rs
  crates/state/src/viewport.rs
  crates/testing/Cargo.toml
  crates/testing/src/test_node.rs
  crates/testing/src/test_utils.rs
  crates/torin/Cargo.toml
  crates/torin/benches/bench.rs
  crates/torin/examples/demo.rs
  crates/torin/src/custom_measurer.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/test_utils.rs
Labels: chore

#573 Improve component docs
  crates/components/src/accordion.rs
  crates/components/src/body.rs
  crates/components/src/button.rs
  crates/components/src/canvas.rs
  crates/components/src/cursor_area.rs
  crates/components/src/drag_drop.rs
  crates/components/src/dropdown.rs
  crates/components/src/gesture_area.rs
  crates/components/src/graph.rs
  crates/components/src/input.rs
  crates/components/src/loader.rs
  crates/components/src/menu.rs
  crates/components/src/network_image.rs
  crates/components/src/popup.rs
  crates/components/src/progress_bar.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/components/src/table.rs
  crates/components/src/theme.rs
  crates/components/src/tile.rs
  crates/components/src/tooltip.rs
Labels: documentation, enhancement 🔥

#577 chore: Clean up docs and imports
  crates/components/Cargo.toml
  crates/components/src/accordion.rs
  crates/components/src/activable_route.rs
  crates/components/src/body.rs
  crates/components/src/button.rs
  crates/components/src/canvas.rs
  crates/components/src/checkbox.rs
  crates/components/src/cursor_area.rs
  crates/components/src/drag_drop.rs
  crates/components/src/dropdown.rs
  crates/components/src/gesture_area.rs
  crates/components/src/graph.rs
  crates/components/src/icons/arrow.rs
  crates/components/src/icons/cross.rs
  crates/components/src/icons/tick.rs
  crates/components/src/input.rs
  crates/components/src/link.rs
  crates/components/src/loader.rs
  crates/components/src/menu.rs
  crates/components/src/native_router.rs
  crates/components/src/network_image.rs
  crates/components/src/popup.rs
  crates/components/src/progress_bar.rs
  crates/components/src/radio.rs
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_thumb.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/snackbar.rs
  crates/components/src/switch.rs
  crates/components/src/table.rs
  crates/components/src/theme.rs
  crates/components/src/tooltip.rs
  crates/core/Cargo.toml
  crates/core/tests/event_bubbling.rs
  crates/core/tests/filedrop_events.rs
  crates/core/tests/pointer_events.rs
  crates/freya/Cargo.toml
  crates/freya/src/_docs/animating.rs
  crates/freya/src/_docs/mod.rs
  crates/freya/src/_docs/testing.rs
  crates/freya/src/_docs/theming.rs
  crates/freya/src/lib.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/src/use_asset_cacher.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_node.rs
  crates/hooks/tests/use_animation.rs
  crates/hooks/tests/use_asset_cacher.rs
  crates/hooks/tests/use_editable.rs
  crates/hooks/tests/use_platform.rs
  crates/native-core/src/tree.rs
  crates/testing/Cargo.toml
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
  crates/testing/tests/test.rs
Labels: documentation, chore

#579 Support-Hex-colors
  crates/elements/src/_docs/color_syntax.rs
  crates/state/src/values/color.rs
  crates/state/tests/parse_color.rs
Labels: enhancement 🔥

#580 fix: Mark text as changed on text cut
  crates/hooks/src/text_editor.rs
Labels: fix 🩹

#583 chore: Relax `TextEditor` bounds
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
Labels: enhancement 🔥

#585 feat: Version counter for changes in EditorHistory
  crates/hooks/src/editor_history.rs
Labels: enhancement 🔥

#587 feat: Controlled keyboard navigation
  crates/common/src/event_messages.rs
  crates/components/src/keyboard_navigator.rs
  crates/components/src/lib.rs
  crates/components/src/menu.rs
  crates/components/src/popup.rs
  crates/devtools/src/lib.rs
  crates/freya/src/launch.rs
  crates/hooks/src/use_accessibility.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/tests/use_focus.rs
  crates/renderer/src/event_loop.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, fix 🩹

#589 feat: Ignore invalid nodes
  crates/core/src/dom/dom_adapter.rs
  crates/core/tests/compatible_elements.rs
  crates/torin/src/measure.rs
Labels: enhancement 🔥

#591 feat: Make `use_node_signal` return a `ReadOnlySignal`
  crates/hooks/src/use_node.rs
Labels: enhancement 🔥

#376 feat: Website enhancements
  README.md
  website/.gitignore
  website/astro.config.mjs
  website/biome.json
  website/package.json
  website/pnpm-lock.yaml
  website/public/blog/0.2/alignment_1.png
  website/public/blog/0.2/alignment_2.png
  website/public/blog/0.2/alignment_3.png
  website/public/blog/0.2/animation.mp4
  website/public/blog/0.2/body.png
  website/public/blog/0.2/checkbox.png
  website/public/blog/0.2/content_fit.png
  website/public/blog/0.2/fill_size.png
  website/public/blog/0.2/ime.png
  website/public/blog/0.2/menu.png
  website/public/blog/0.2/performance_plugin.png
  website/public/blog/0.2/popup.png
  website/public/blog/0.2/progress_bar.png
  website/public/blog/0.2/radio.png
  website/public/blog/0.2/sidebar.png
  website/public/blog/0.2/table.png
  website/public/blog/announcement/canvas.png
  website/public/blog/announcement/demo.png
  website/public/blog/announcement/devtools.png
  website/public/blog/announcement/freya_editor.jpg
  website/public/demo.mp4
  website/public/preview.png
  website/src/components/BlogPostTOC.astro
  website/src/components/Card.astro
  website/src/components/Codeblock.jsx
  website/src/components/Navbar.astro
  website/src/content/blog/0.2.md
  website/src/content/blog/announcement.md
  website/src/env.d.ts
  website/src/layouts/BlogPostLayout.astro
  website/src/layouts/Layout.astro
  website/src/pages/blog.astro
  website/src/pages/index.astro
  website/src/pages/posts/[...slug].astro
  website/src/pages/rss.xml.js
  website/tailwind.config.mjs
Labels: website🌐, waiting-for-release

#570 feat: Revamped book
  book/src/SUMMARY.md
  book/src/contact.md
  book/src/differences_with_dioxus.md
  book/src/dioxus.md
  book/src/faq.md
  book/src/getting_started.md
  book/src/guides/animating.md
  book/src/guides/components.md
  book/src/guides/devtools.md
  book/src/guides/effects.md
  book/src/guides/elements.md
  book/src/guides/font_style.md
  book/src/guides/getting_started.md
  book/src/guides/hot_reload.md
  book/src/guides/layout.md
  book/src/guides/publishing.md
  book/src/guides/style.md
  book/src/guides/testing.md
  book/src/guides/theming.md
  book/src/guides/virtual_scroll_view.png
  book/src/guides/virtualizing.md
  book/src/index.md
  book/src/setup.md
  book/src/what_is_freya.md
Labels: documentation, enhancement 🔥, waiting-for-release

#493 chore: Bump crates
  Cargo.toml
  README.md
  crates/common/Cargo.toml
  crates/components/Cargo.toml
  crates/core/Cargo.toml
  crates/devtools/Cargo.toml
  crates/elements/Cargo.toml
  crates/engine/Cargo.toml
  crates/freya/Cargo.toml
  crates/hooks/Cargo.toml
  crates/native-core-macro/Cargo.toml
  crates/native-core/Cargo.toml
  crates/renderer/Cargo.toml
  crates/state/Cargo.toml
  crates/testing/Cargo.toml
  crates/torin/Cargo.toml
Labels: release 📆
