Repository marc2332/freya, pull requests merged in 2025-01, with the labels that each got.

#1036 docs: fix typos and improve text in "Differences with Dioxus" section
  book/src/differences_with_dioxus.md
Labels: documentation

#1031 fix: Consider flex elements in incremental layout
  crates/torin/src/node.rs
  crates/torin/tests/flex.rs
Labels: fix 🩹, layout 📐

#1037 fix: Add missing `Data` to `[u8]` deref
  crates/engine/src/mocked.rs
Labels: fix 🩹, skia 🖌️

#1034 feat: Support incremental rendering in `use_camera` hook
  crates/elements/src/definitions.rs
  crates/hooks/src/use_camera.rs
  crates/hooks/src/use_node.rs
  examples/camera.rs
Labels: fix 🩹

#1035 feat: Type safety for `use_animation`
  crates/components/src/accordion.rs
  crates/components/src/animated_position.rs
  crates/components/src/loader.rs
  crates/components/src/overflowed_content.rs
  crates/components/src/snackbar.rs
  crates/components/src/switch.rs
  crates/hooks/src/lib.rs
  crates/hooks/src/use_animation.rs
  crates/hooks/tests/use_animation.rs
  examples/animated_sidebar.rs
  examples/animated_tabs.rs
  examples/animated_virtual_scroll_view.rs
  examples/animation.rs
  examples/performance_overlay_plugin.rs
  examples/progress_bar.rs
  examples/snackbar.rs
  examples/speedometer.rs
Labels: enhancement 🔥

#1032 feat: Simplify `use_asset_cacher` hook
  crates/components/src/network_image.rs
  crates/hooks/Cargo.toml
  crates/hooks/src/use_asset_cacher.rs
  crates/hooks/tests/use_asset_cacher.rs
Labels: enhancement 🔥, internal impovement👍

#1038 fix: Add custom SendAnyMap for torin to not depend on freya-native-core
  crates/core/src/render/skia_measurer.rs
  crates/torin/benches/bench.rs
  crates/torin/examples/demo.rs
  crates/torin/src/custom_measurer.rs
  crates/torin/src/dom_adapter.rs
  crates/torin/src/lib.rs
  crates/torin/src/sendanymap.rs
  crates/torin/src/test_utils.rs
Labels: enhancement 🔥, fix 🩹

#1044 chore: Remove Dioxus hot-reload support
  Cargo.toml
  crates/freya/Cargo.toml
  crates/freya/src/lib.rs
  crates/renderer/Cargo.toml
  crates/renderer/src/renderer.rs
  examples/hotreload.rs
Labels: internal impovement👍

#1047 feat: Allow `FnOnce` closures in window callbacks
  crates/renderer/src/config.rs
  crates/renderer/src/renderer.rs
Labels: enhancement 🔥

#1045 feat: Move the size options of NetworkImage from its theme to its props
  crates/components/src/network_image.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  examples/accessibility.rs
Labels: enhancement 🔥

#1048 fix: Poll one more time the overflowed content test
  crates/components/src/overflowed_content.rs
Labels: fix 🩹, internal impovement👍

#1054 docs: Update Windows's setup instructions
  book/src/setup.md
  crates/freya/src/_docs/development_setup.rs
Labels: documentation

#1039 feat: Improve dropdown styling
  crates/components/src/dropdown.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
Labels: enhancement 🔥

#1052 refactor: Use Rc<Refcell<T>> instead of Arc<Mutex<T>> when sharing the DOM
  crates/core/Cargo.toml
  crates/core/src/dom/doms.rs
  crates/devtools/Cargo.toml
  crates/testing/Cargo.toml
  crates/testing/src/test_handler.rs
Labels: internal impovement👍

#1053 feat: Show role alongside tag in devtools inspector
  crates/core/src/node.rs
  crates/devtools/Cargo.toml
  crates/devtools/src/node.rs
Labels: enhancement 🔥

#1046 fix: Manually drop previous animated values when the run callback reruns
  crates/hooks/src/use_animation.rs
Labels: internal impovement👍

#1041 feat: `OnDepsChange::Rerun` for `use_animation`
  crates/hooks/src/use_animation.rs
Labels: enhancement 🔥

#1058 feat: Delegated focus
  crates/freya/src/lib.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_platform.rs
  examples/delegated_focus.rs
Labels: enhancement 🔥

#1061 feat: `onvalidate` function for `Input`
  crates/components/src/hooks/use_form.rs
  crates/components/src/input.rs
  crates/hooks/src/editor_history.rs
  crates/hooks/src/rope_editor.rs
  crates/hooks/src/text_editor.rs
  examples/input.rs
Labels: enhancement 🔥

#1056 feat: Redesign devtools inspector
  crates/components/src/link.rs
  crates/components/src/tabs.rs
  crates/devtools/Cargo.toml
  crates/devtools/src/lib.rs
  crates/devtools/src/node.rs
  crates/devtools/src/property.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/hooks/src/theming/mod.rs
  crates/torin/src/values/size.rs
Labels: enhancement 🔥, devtools

#1064 feat: Improve `text_overflow` docs
  crates/elements/src/_docs/attributes/text_overflow.md
  crates/state/src/values/font.rs
Labels: documentation, enhancement 🔥

#1067 fix: Events triggering fixes
  crates/components/src/button.rs
  crates/components/src/drag_drop.rs
  crates/components/src/gesture_area.rs
  crates/components/src/input.rs
  crates/components/src/native_router.rs
  crates/components/src/popup.rs
  crates/components/src/resizable_container.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/core/src/events/dom_event.rs
  crates/core/src/events/event_name.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/mod.rs
  crates/core/src/events/nodes_state.rs
  crates/core/src/events/platform_event.rs
  crates/core/src/events/potential_event.rs
  crates/core/src/plugins.rs
  crates/core/tests/event_bubbling.rs
  crates/core/tests/events_emitting.rs
  crates/core/tests/filedrop_events.rs
  crates/core/tests/pointer_events.rs
  crates/elements/src/definitions.rs
  crates/elements/src/events/file.rs
  crates/elements/src/events/keyboard.rs
  crates/elements/src/events/mouse.rs
  crates/elements/src/events/pointer.rs
  crates/elements/src/events/touch.rs
  crates/elements/src/events/wheel.rs
  crates/freya/src/plugins/performance_overlay.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/tests/use_editable.rs
  crates/hooks/tests/use_focus.rs
  crates/renderer/src/app.rs
  crates/renderer/src/renderer.rs
  crates/testing/src/event.rs
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
  examples/gamepad_focus.rs
  examples/gamepad_trace.rs
Labels: fix 🩹

#1040 feat: Support `a11y_member_of`
  crates/components/src/dropdown.rs
  crates/core/src/platform_state.rs
  crates/core/src/types.rs
  crates/elements/src/definitions.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/native-core/src/attributes.rs
  crates/renderer/src/accessibility.rs
  crates/renderer/src/app.rs
  crates/state/src/accessibility.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
Labels: enhancement 🔥, accessibility 🦾

#1042 feat: `aspect_ratio` for `image`
  crates/components/src/network_image.rs
  crates/core/src/elements/image.rs
  crates/elements/src/_docs/ferris.svg
  crates/elements/src/_docs/rust_logo.png
  crates/elements/src/attributes/image_attributes.rs
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/native-core/src/attributes.rs
  crates/state/src/transform.rs
  crates/state/src/values/aspect_ratio.rs
  crates/state/src/values/mod.rs
  examples/images_slideshow.rs
Labels: enhancement 🔥

#1072 feat: `visible_width` & `visible_height`
  crates/components/src/accordion.rs
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/node.rs
  crates/devtools/src/tabs/style.rs
  crates/elements/src/attributes/layout_attributes.rs
  crates/elements/src/elements.rs
  crates/native-core/src/attributes.rs
  crates/state/src/layout.rs
  crates/state/src/values/mod.rs
  crates/state/src/values/size.rs
  crates/state/src/values/visible_size.rs
  crates/torin/src/geometry.rs
  crates/torin/src/node.rs
  crates/torin/src/values/mod.rs
  crates/torin/src/values/size.rs
  crates/torin/src/values/visible_size.rs
  crates/torin/tests/flex.rs
  crates/torin/tests/size.rs
Labels: enhancement 🔥

#941 feat: `scale` effect
  crates/components/src/popup.rs
  crates/core/src/elements/rect.rs
  crates/core/src/elements/utils.rs
  crates/core/src/render/compositor.rs
  crates/core/src/render/pipeline.rs
  crates/elements/src/attributes/transform_attributes.rs
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/hooks/src/use_animation.rs
  crates/native-core/src/attributes.rs
  crates/state/src/transform.rs
  examples/animated_position.rs
  examples/animation.rs
  examples/drag_drop.rs
Labels: enhancement 🔥

#1076 feat: Infinite list example
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/use_scroll_controller.rs
  crates/hooks/src/use_node.rs
  examples/infinite_list.rs
Labels: enhancement 🔥

#905 docs: Components Previews
  .github/workflows/deploy_docs.yml
  crates/components/Cargo.toml
  crates/components/images/gallery_bottom_tab.png
  crates/components/images/gallery_button.png
  crates/components/images/gallery_checkbox.png
  crates/components/images/gallery_dropdown.png
  crates/components/images/gallery_enabled_switch.png
  crates/components/images/gallery_filled_button.png
  crates/components/images/gallery_input.png
  crates/components/images/gallery_loader.png
  crates/components/images/gallery_menu.png
  crates/components/images/gallery_network_image.png
  crates/components/images/gallery_not_enabled_switch.png
  crates/components/images/gallery_outline_button.png
  crates/components/images/gallery_progress_bar.png
  crates/components/images/gallery_radio.png
  crates/components/images/gallery_scroll_view.png
  crates/components/images/gallery_slider.png
  crates/components/images/gallery_snackbar.png
  crates/components/images/gallery_tab.png
  crates/components/images/gallery_tooltip.png
  crates/components/images/gallery_virtual_scroll_view.png
  crates/components/src/button.rs
  crates/components/src/checkbox.rs
  crates/components/src/dropdown.rs
  crates/components/src/input.rs
  crates/components/src/lib.rs
  crates/components/src/loader.rs
  crates/components/src/menu.rs
  crates/components/src/network_image.rs
  crates/components/src/progress_bar.rs
  crates/components/src/radio.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/snackbar.rs
  crates/components/src/svg.rs
  crates/components/src/switch.rs
  crates/components/src/tabs.rs
  crates/components/src/tooltip.rs
  crates/freya/src/lib.rs
  crates/testing/src/launch.rs
Labels: documentation, enhancement 🔥

#1079 fix: Check layout exists for collateral events
  crates/core/src/events/nodes_state.rs
Labels: fix 🩹
