Repository marc2332/freya, pull requests merged in 2025-05, with the labels that each got.

#1157 fix: Update the navigation mode after the accessibility update
  crates/winit/src/app.rs
  crates/winit/src/renderer.rs
Labels: fix 🩹

#1159 fix: Prevent animations stalling
  crates/hooks/src/use_animation/anim_color.rs
  crates/hooks/src/use_animation/anim_num.rs
  crates/hooks/src/use_animation/animated_value.rs
  examples/animated_tabs.rs
Labels: fix 🩹

#1158 chore: Update accesskit, skia-safe and others
  Cargo.toml
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/states/accessibility.rs
  crates/core/src/values/accessibility.rs
  crates/devtools/Cargo.toml
  crates/devtools/src/node.rs
  crates/native-core/src/attributes.rs
  crates/native-core/src/passes.rs
  crates/native-core/src/real_dom.rs
  crates/native-core/src/tree.rs
  crates/testing/src/launch.rs
  crates/winit/src/accessibility.rs
  crates/winit/src/app.rs
  crates/winit/src/config.rs
  crates/winit/src/renderer.rs
  crates/winit/src/window_state.rs
  examples/dioxus_query.rs
  rust-toolchain.toml
Labels: internal impovement👍

#1163 fix: Only send release events on pressed nodes
  crates/components/src/popup.rs
  crates/core/src/events/nodes_state.rs
  crates/native-core/src/events.rs
Labels: fix 🩹

#1165 fix: Only update devtools on repaint or relayout, but not both
  crates/winit/src/app.rs
  crates/winit/src/devtools.rs
Labels: fix 🩹

#1174 fix: Margin should not be applied again after auto measurement
  crates/torin/src/measure.rs
  crates/torin/tests/size.rs
Labels: fix 🩹

#1181 fix: Do not bubble keyboard global events
  crates/core/tests/events_emitting.rs
  crates/native-core/src/events.rs
Labels: fix 🩹

#1183 refactor: Remove `pin-utils` dep
  Cargo.toml
  crates/winit/Cargo.toml
  crates/winit/src/app.rs
Labels: enhancement 🔥

#1189 refactor: Only enable `embed-doc-image` in `docs` feature
  crates/components/Cargo.toml
Labels: enhancement 🔥, dependencies

#1188 chore: Update descriptions
  README.md
  crates/freya/Cargo.toml
  website/src/pages/index.astro
Labels: documentation

#1195 Feat: customizable loader size
  crates/components/src/loader.rs
  examples/loader.rs
Labels: enhancement 🔥
