Repository marc2332/freya, pull requests merged in 2025-06, with the labels that each got.

#1206 docs: add example for conditional rendering
  examples/conditional_rendering.rs
Labels: documentation

#1205 HEX transparency
  crates/core/src/values/color.rs
  crates/core/tests/parse_color.rs
Labels: enhancement 🔥

#1197 feat: Support `main_align` and `cross_align` in `Body` component
  crates/components/src/body.rs
  examples/button.rs
  examples/documents_editor.rs
  examples/preferred_theme.rs
  examples/router.rs
  examples/shader_editor.rs
  examples/tab.rs
Labels: enhancement 🔥

#1216 fix: Do not focus `VirtualScrollView` on scroll
  crates/components/src/scroll_views/virtual_scroll_view.rs
Labels: fix 🩹

#1219 feat: Smooth scrolling horizontal for `VirtualScrollview`
  crates/components/src/scroll_views/virtual_scroll_view.rs
  examples/horizontal_virtual_scroll_view.rs
Labels: enhancement 🔥

#1226 Fix animated tabs file reference
  README.md
Labels: documentation, fix 🩹

#1233 Consider 'grey' a valid syntax colour
  crates/core/src/values/color.rs
  crates/elements/src/_docs/color_syntax.rs
  crates/engine/src/mocked.rs
Labels: enhancement 🔥

#924 feat: backdrop blurring and blend modes
  crates/core/src/elements/rect.rs
  crates/core/src/render/pipeline.rs
  crates/core/src/states/transform.rs
  crates/core/src/values/blend_mode.rs
  crates/core/src/values/corner_radius.rs
  crates/core/src/values/mod.rs
  crates/core/tests/parse_blend_mode.rs
  crates/elements/src/attributes/style_attributes.rs
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/native-core/src/attributes.rs
  examples/backdrop_blur.rs
  examples/blend_mode.rs
  examples/wallpaper.png
Labels: enhancement 🔥

#1239 feat: Docs example in `Table` component
  crates/components/src/table.rs
Labels: documentation

#1241 fix: Remove non important dioxus warnings
  crates/components/Cargo.toml
  crates/components/src/input.rs
  crates/components/src/scroll_views/use_scroll_controller.rs
Labels: internal impovement👍

#1244 fix: Clear the selection of `SelectableText` when it gets clicked out
  crates/components/src/selectable_text.rs
  examples/selectable_text.rs
Labels: fix 🩹

#1118 feat: Replace selected text on paste
  crates/hooks/src/text_editor.rs
Labels: enhancement 🔥

#1235 refactor: Update how accessibility tasks are managed
  crates/core/src/platform_state.rs
  crates/winit/src/app.rs
  crates/winit/src/renderer.rs
Labels: internal impovement👍

#1262 feat: Add `corner_radius` and `padding` to `SidebarItemTheme`
  crates/components/src/sidebar.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
Labels: enhancement 🔥

#1260 feat: Re-export dioxus
  Cargo.toml
  crates/freya/src/lib.rs
Labels: enhancement 🔥

#1263 feat: Add `AnimationClock` to universally slow down or speed up animations
  crates/core/src/animation_clock.rs
  crates/core/src/dom/doms.rs
  crates/core/src/lib.rs
  crates/freya/src/lib.rs
  crates/freya/src/plugins/performance_overlay.rs
  crates/hooks/src/use_animation/hook.rs
  crates/testing/src/test_handler.rs
  crates/winit/Cargo.toml
  crates/winit/src/app.rs
  crates/winit/src/renderer.rs
Labels: enhancement 🔥

#1269 feat: Extended `on_creation` configuration in `use_animation`
  crates/components/src/loader.rs
  crates/components/src/popup.rs
  crates/hooks/src/use_animation/anim_color.rs
  crates/hooks/src/use_animation/anim_num.rs
  crates/hooks/src/use_animation/hook.rs
  crates/hooks/tests/use_animation.rs
  examples/animated_hover.rs
  examples/animated_position.rs
  examples/animated_virtual_scroll_view.rs
  examples/drag_drop.rs
  examples/images_slideshow.rs
  examples/todo.rs
Labels: enhancement 🔥

#1270 refactor: Simplify the internals of `use_animation`
  crates/components/src/animated_position.rs
  crates/components/src/global_animated_position.rs
  crates/hooks/src/use_animation/hook.rs
Labels: enhancement 🔥, internal impovement👍

#1240 docs: Clarify `fill` size value
  crates/elements/src/_docs/size_unit.rs
Labels: documentation

#1255 feat: Rethink `AssetCacher`
  crates/components/src/network_image.rs
  crates/hooks/src/use_asset_cacher.rs
  crates/hooks/src/use_init_native_platform.rs
  crates/hooks/tests/use_asset_cacher.rs
Labels: enhancement 🔥

#1272 feat: Global error boundary for Freya apps
  crates/freya/src/launch.rs
  examples/error_boundary.rs
Labels: enhancement 🔥

#1274 fix: Update codecov config
  codecov.yml
Labels: fix 🩹, internal impovement👍

#1238 feat: `UsePlatform::sender`
  crates/components/src/native_container.rs
  crates/hooks/src/use_focus.rs
  crates/hooks/src/use_platform.rs
  examples/delegated_focus.rs
Labels: enhancement 🔥

#1236 Add .editorconfig
  .editorconfig
Labels: internal impovement👍

#1266 feat: `onpointerpress` event
  crates/components/src/button.rs
  crates/core/tests/events_emitting.rs
  crates/elements/src/events/pointer.rs
  crates/native-core/src/events.rs
Labels: enhancement 🔥

#1257 feat: Make `winit` optional in core crates
  .github/workflows/rust.yml
  crates/components/Cargo.toml
  crates/components/src/lib.rs
  crates/core/Cargo.toml
  crates/core/src/event_loop_messages.rs
  crates/core/src/events/platform_event.rs
  crates/core/src/platform/mod.rs
  crates/core/src/platform/mouse.rs
  crates/core/src/platform/pointer.rs
  crates/core/src/platform/touch.rs
  crates/core/src/platform/window.rs
  crates/devtools/Cargo.toml
  crates/elements/Cargo.toml
  crates/elements/src/events/mouse.rs
  crates/elements/src/events/pointer.rs
  crates/elements/src/events/touch.rs
  crates/freya/Cargo.toml
  crates/hooks/Cargo.toml
  crates/hooks/src/use_platform.rs
  crates/testing/Cargo.toml
  crates/testing/src/lib.rs
  crates/testing/src/test_handler.rs
  crates/winit/Cargo.toml
  crates/winit/src/events.rs
  crates/winit/src/lib.rs
  crates/winit/src/renderer.rs
Labels: enhancement 🔥, internal impovement👍

#1277 fix: Only close accordion when summary is clicked
  crates/components/src/accordion.rs
  examples/accordion.rs
Labels: fix 🩹

#1278 fix: Only discard cancelled events in the same run
  crates/components/src/resizable_container.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/handler.rs
  crates/core/src/events/nodes_state.rs
  crates/core/src/types.rs
  crates/native-core/src/events.rs
  crates/testing/src/test_handler.rs
  crates/winit/src/app.rs
Labels: fix 🩹, internal impovement👍

#1279 refactor: Make `freya-native-core`'s NodeId a wrapper type rather than type alias
  crates/devtools/src/lib.rs
  crates/devtools/src/tabs/layout.rs
  crates/devtools/src/tabs/style.rs
  crates/devtools/src/tabs/tree.rs
  crates/native-core-macro/src/lib.rs
  crates/native-core/Cargo.toml
  crates/native-core/src/lib.rs
  crates/native-core/src/node_id.rs
  crates/native-core/src/real_dom.rs
  crates/native-core/src/tree.rs
  crates/torin/Cargo.toml
  crates/torin/src/dom_adapter.rs
Labels: internal impovement👍

#1287 fix: Disable default features in `dioxus-lib`
  Cargo.toml
  crates/components/images/gallery_bottom_tab.png
  crates/components/images/gallery_button.png
  crates/components/images/gallery_dropdown.png
  crates/components/images/gallery_enabled_switch.png
  crates/components/images/gallery_filled_button.png
  crates/components/images/gallery_input.png
  crates/components/images/gallery_loader.png
  crates/components/images/gallery_menu.png
  crates/components/images/gallery_outline_button.png
  crates/components/images/gallery_progress_bar.png
  crates/components/images/gallery_scroll_view.png
  crates/components/images/gallery_slider.png
  crates/components/images/gallery_snackbar.png
  crates/components/images/gallery_tab.png
  crates/components/images/gallery_tooltip.png
  crates/components/images/gallery_virtual_scroll_view.png
  crates/router/src/components/child_router.rs
  crates/router/src/contexts/outlet.rs
Labels: fix 🩹

#1280 feat: `ragnarok` crate, UI events processor library
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/events/dom_event.rs
  crates/core/src/events/events_measurer.rs
  crates/core/src/events/executor.rs
  crates/core/src/events/handler.rs
  crates/core/src/events/measurer.rs
  crates/core/src/events/mod.rs
  crates/core/src/events/nodes_state.rs
  crates/core/src/events/platform_event.rs
  crates/core/src/events/potential_event.rs
  crates/core/src/layout.rs
  crates/core/src/types.rs
  crates/core/src/values/gradient.rs
  crates/native-core/Cargo.toml
  crates/native-core/src/events.rs
  crates/native-core/src/node_id.rs
  crates/ragnarok/Cargo.toml
  crates/ragnarok/README.md
  crates/ragnarok/src/emmitable.rs
  crates/ragnarok/src/executor.rs
  crates/ragnarok/src/key.rs
  crates/ragnarok/src/lib.rs
  crates/ragnarok/src/measurement.rs
  crates/ragnarok/src/measurer.rs
  crates/ragnarok/src/name.rs
  crates/ragnarok/src/nodes_state.rs
  crates/ragnarok/src/potential_event.rs
  crates/ragnarok/src/source.rs
  crates/ragnarok/tests/state.rs
  crates/testing/Cargo.toml
  crates/testing/src/launch.rs
  crates/testing/src/test_handler.rs
  crates/torin/src/geometry.rs
  crates/winit/Cargo.toml
  crates/winit/src/app.rs
Labels: enhancement 🔥, internal impovement👍

#1283 feat: Clear distinction between fallback and default fonts
  crates/core/src/elements/image.rs
  crates/core/src/elements/label.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/elements/rect.rs
  crates/core/src/elements/svg.rs
  crates/core/src/elements/utils.rs
  crates/core/src/layout.rs
  crates/core/src/render/pipeline.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/render/utils/label.rs
  crates/core/src/render/utils/paragraph.rs
  crates/core/src/states/font_style.rs
  crates/core/src/style.rs
  crates/testing/src/test_handler.rs
  crates/winit/src/app.rs
  crates/winit/src/config.rs
  crates/winit/src/window_state.rs
  examples/embedded_font.rs
  examples/stateful_window.rs
Labels: enhancement 🔥

#1275 feat: Scroll to focused node when tabbing
  crates/components/src/scroll_views/scroll_view.rs
  crates/core/src/accessibility/tree.rs
  crates/core/src/dom/doms.rs
  crates/core/src/events/dom_event.rs
  crates/core/src/states/mod.rs
  crates/core/src/states/scrollable.rs
  crates/core/src/states/viewport.rs
  crates/core/tests/scroll_to_focused.rs
  crates/elements/src/events/wheel.rs
  crates/testing/src/test_handler.rs
  crates/testing/src/test_node.rs
  crates/winit/src/accessibility.rs
  crates/winit/src/app.rs
  examples/scroll_to_focused.rs
  examples/ui.rs
Labels: enhancement 🔥

#1286 feat: Dynamic resizable container
  crates/components/src/resizable_container.rs
  crates/core/src/node.rs
  crates/devtools/src/lib.rs
  crates/winit/src/devtools.rs
  examples/resizable_container.rs
Labels: enhancement 🔥

#1273 feat: Add `SegmentedButton` component
  crates/components/images/gallery_segmented_button.png
  crates/components/src/lib.rs
  crates/components/src/segmented_button.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  examples/segmented_button.rs
Labels: enhancement 🔥
