Repository marc2332/freya, pull requests merged in 2025-02, with the labels that each got.

#1081 feat: Images cache
  crates/common/src/images_cache.rs
  crates/common/src/lib.rs
  crates/components/src/network_image.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/elements/image.rs
  crates/core/src/elements/label.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/elements/rect.rs
  crates/core/src/elements/svg.rs
  crates/core/src/elements/utils.rs
  crates/core/src/render/pipeline.rs
  crates/core/tests/freya.png
  crates/core/tests/images_cache.rs
  crates/elements/src/attributes/image_attributes.rs
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/native-core/src/attributes.rs
  crates/renderer/src/app.rs
  crates/state/src/style.rs
  crates/testing/src/test_handler.rs
  examples/image.rs
  examples/image_cache_key.rs
Labels: enhancement 🔥

#1078 feat: `cover` attribute for `image` element
  crates/components/src/network_image.rs
  crates/core/src/elements/image.rs
  crates/elements/src/attributes/image_attributes.rs
  crates/elements/src/elements.rs
  crates/native-core/src/attributes.rs
  crates/state/src/transform.rs
  crates/state/src/values/image_cover.rs
  crates/state/src/values/mod.rs
  examples/images_slideshow.rs
Labels: enhancement 🔥

#1080 Add `sampling` property for `image`
  crates/components/src/network_image.rs
  crates/core/src/elements/image.rs
  crates/elements/src/attributes/image_attributes.rs
  crates/elements/src/elements.rs
  crates/engine/src/mocked.rs
  crates/engine/src/skia.rs
  crates/native-core/src/attributes.rs
  crates/state/src/style.rs
  crates/state/src/values/mod.rs
  crates/state/src/values/sampling.rs
  examples/image_sampling.rs
Labels: enhancement 🔥

#1083 refactor: Improved `UseFocus::validate_keydown`
  crates/components/src/button.rs
  crates/components/src/checkbox.rs
  crates/components/src/dropdown.rs
  crates/components/src/radio.rs
  crates/components/src/slider.rs
  crates/components/src/switch.rs
  crates/components/src/tabs.rs
  crates/components/src/tile.rs
  crates/hooks/src/use_focus.rs
Labels: enhancement 🔥

#1082 feat: Integrate images into layout
  crates/components/src/network_image.rs
  crates/core/src/elements/image.rs
  crates/core/src/layout.rs
  crates/core/src/render/skia_measurer.rs
  crates/core/src/render/utils/image.rs
  crates/core/src/render/utils/mod.rs
  crates/elements/src/attributes/image_attributes.rs
  crates/elements/src/elements.rs
  crates/freya/src/_docs/elements.rs
  crates/state/src/style.rs
  crates/state/src/values/aspect_ratio.rs
  examples/app_dog.rs
  examples/camera.rs
  examples/image.rs
  examples/image_aspect_ratio.rs
  examples/image_sampling.rs
  examples/image_viewer.rs
  examples/images_slideshow.rs
  examples/infinite_list.rs
Labels: enhancement 🔥

#1028 feat: New `GlobalAnimatedPosition` component
  crates/components/src/global_animated_position.rs
  crates/components/src/lib.rs
  examples/grid_shuffle.rs
Labels: enhancement 🔥

#1086 feat: Cooler animated tabs example
  Cargo.toml
  examples/animated_tabs.rs
Labels: enhancement 🔥

#1089 chore: Update to skia-safe v0.81.0
  Cargo.toml
Labels: internal impovement👍

#1096 fix(core): Don't reverse unnecessary nodes in event measurer
  .github/workflows/rust.yml
  Cargo.toml
  crates/core/src/events/events_measurer.rs
Labels: fix 🩹, ci-cd 🤖

#1099 fix: Clip scale effects
  crates/core/src/render/pipeline.rs
Labels: fix 🩹

#1100 feat: Dioxus 0.6.3
  Cargo.toml
Labels: enhancement 🔥, dependencies

#1097 feat: UI Improvements
  crates/components/images/gallery_bottom_tab.png
  crates/components/images/gallery_button.png
  crates/components/images/gallery_checkbox.png
  crates/components/images/gallery_dropdown.png
  crates/components/images/gallery_enabled_switch.png
  crates/components/images/gallery_filled_button.png
  crates/components/images/gallery_input.png
  crates/components/images/gallery_loader.png
  crates/components/images/gallery_menu.png
  crates/components/images/gallery_network_image.png
  crates/components/images/gallery_not_enabled_switch.png
  crates/components/images/gallery_outline_button.png
  crates/components/images/gallery_progress_bar.png
  crates/components/images/gallery_radio.png
  crates/components/images/gallery_scroll_view.png
  crates/components/images/gallery_slider.png
  crates/components/images/gallery_snackbar.png
  crates/components/images/gallery_tab.png
  crates/components/images/gallery_tooltip.png
  crates/components/images/gallery_virtual_scroll_view.png
  crates/components/src/body.rs
  crates/components/src/button.rs
  crates/components/src/checkbox.rs
  crates/components/src/dropdown.rs
  crates/components/src/hooks/use_form.rs
  crates/components/src/input.rs
  crates/components/src/link.rs
  crates/components/src/loader.rs
  crates/components/src/menu.rs
  crates/components/src/network_image.rs
  crates/components/src/progress_bar.rs
  crates/components/src/radio.rs
  crates/components/src/scroll_views/mod.rs
  crates/components/src/scroll_views/scroll_bar.rs
  crates/components/src/scroll_views/scroll_thumb.rs
  crates/components/src/scroll_views/scroll_view.rs
  crates/components/src/scroll_views/virtual_scroll_view.rs
  crates/components/src/slider.rs
  crates/components/src/snackbar.rs
  crates/components/src/switch.rs
  crates/components/src/table.rs
  crates/components/src/tabs.rs
  crates/components/src/tooltip.rs
  crates/core/src/render/compositor.rs
  crates/core/src/states/style.rs
  crates/core/src/values/color.rs
  crates/core/src/values/fill.rs
  crates/elements/src/attributes/style_attributes.rs
  crates/elements/src/elements.rs
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/theming/themes.rs
  crates/native-core/src/attributes.rs
  crates/torin/src/measure.rs
  crates/torin/src/node.rs
  examples/dropdown.rs
  examples/input.rs
  examples/menu.rs
  examples/scroll.rs
  examples/table.rs
Labels: enhancement 🔥

#1103 refactor: Per node states and lazy scaling
  crates/components/images/gallery_enabled_switch.png
  crates/components/src/input.rs
  crates/core/src/dom/dom_adapter.rs
  crates/core/src/dom/doms.rs
  crates/core/src/dom/mutations_writer.rs
  crates/core/src/elements/image.rs
  crates/core/src/elements/label.rs
  crates/core/src/elements/paragraph.rs
  crates/core/src/elements/rect.rs
  crates/core/src/elements/svg.rs
  crates/core/src/node.rs
  crates/core/src/render/utils/borders.rs
  crates/core/src/render/utils/image.rs
  crates/core/src/render/utils/shadows.rs
  crates/core/src/states/canvas.rs
  crates/core/src/states/cursor.rs
  crates/core/src/states/font_style.rs
  crates/core/src/states/image.rs
  crates/core/src/states/mod.rs
  crates/core/src/states/style.rs
  crates/core/src/states/svg.rs
  crates/core/src/states/transform.rs
  crates/core/src/values/fill.rs
  crates/core/tests/parse_border.rs
  crates/core/tests/parse_shadows.rs
  crates/elements/src/elements.rs
  crates/hooks/tests/use_editable.rs
  crates/native-core-macro/src/lib.rs
  crates/native-core/src/passes.rs
  crates/torin/src/scaled.rs
  examples/cloned_editor.rs
  examples/documents_editor.rs
  examples/floating_editors.rs
  examples/shader_editor.rs
  examples/simple_editor.rs
  examples/text_editors.rs
Labels: performance ⚡️, internal impovement👍

#1104 fix: Stretch input's paragraph width
  crates/components/src/input.rs
Labels: fix 🩹

#1106 feat: Render the input placeholder even when its focused
  crates/components/src/input.rs
Labels: enhancement 🔥

#1108 feat: `todo.rs` example and some fixes
  crates/components/src/drag_drop.rs
  crates/components/src/popup.rs
  crates/core/src/elements/utils.rs
  crates/core/src/states/layout.rs
  crates/torin/src/measure.rs
  crates/torin/src/values/position.rs
  examples/todo.rs
Labels: enhancement 🔥, fix 🩹

#1105 docs: Finish 0.3.0 docs
  crates/elements/src/attributes/layout_attributes.rs
  crates/freya/src/_docs/accessibility.rs
  crates/freya/src/_docs/async_tasks.rs
  crates/freya/src/_docs/components_and_props.rs
  crates/freya/src/_docs/hooks.rs
  crates/freya/src/_docs/introduction.rs
  crates/freya/src/_docs/mod.rs
  crates/freya/src/_docs/router.rs
  crates/freya/src/_docs/router/animated_transitions.rs
  crates/freya/src/_docs/router/native_router.rs
  crates/freya/src/_docs/state_management.rs
  crates/freya/src/_docs/state_management/context.rs
  crates/freya/src/_docs/state_management/lifecycle.rs
  crates/freya/src/_docs/state_management/signals.rs
  crates/freya/src/_docs/theming.rs
  crates/freya/src/_docs/ui.rs
  crates/freya/src/launch.rs
  crates/freya/src/lib.rs
  crates/hooks/src/use_focus.rs
  crates/winit/src/config.rs
Labels: documentation

#1110 feat: support for `current_color` in the svg attributes `fill` and `stroke`.
  crates/core/src/elements/svg.rs
  crates/core/src/node.rs
  crates/core/src/states/svg.rs
  crates/core/src/values/mod.rs
  crates/core/src/values/paint.rs
  crates/elements/src/_docs/color_syntax.rs
  crates/elements/src/attributes/svg_attributes.rs
  crates/engine/src/mocked.rs
  examples/svg_fill.rs
Labels: enhancement 🔥

#1111 feat: Use a darker color for the focused border of `FilledButton`
  crates/hooks/src/theming/base.rs
  crates/hooks/src/theming/mod.rs
  crates/hooks/src/theming/themes.rs
Labels: enhancement 🔥
